// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/JavaTimeInstantFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:40:01 GMT 2024
 */
package com.zappos.json.format;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import com.zappos.json.format.ValueFormatter;
import java.time.DateTimeException;
import java.time.Instant;
import java.time.format.DateTimeParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JavaTimeInstantFormatter_ESTest extends JavaTimeInstantFormatter_ESTest_scaffolding {

    
    @Test
    public void testFormat_withAndWithoutFormatter() {
        JavaTimeInstantFormatter formatter = new JavaTimeInstantFormatter();
        ZapposJson zapposJson = ZapposJson.getInstance();
        Instant instant = Instant.ofEpochMilli(123456789L);

        // Test without formatter: should return epoch millis as string without quotes
        String resultWithoutFormatter = formatter.format(zapposJson, instant);
        assertEquals("123456789", resultWithoutFormatter);

        // Test with formatter: should return formatted string wrapped in quotes (JSON string)
        JavaTimeInstantFormatter formatterWithPattern = (JavaTimeInstantFormatter) formatter.newInstance();
        formatterWithPattern.setPattern("yyyy-MM-dd'T'HH:mm:ss'Z'");
        String resultWithFormatter = formatterWithPattern.format(zapposJson, instant);
        assertEquals("\"1970-01-02T10:17:36Z\"", resultWithFormatter);
    }
}
