// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonWriter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:01:13 GMT 2024
 */
package com.zappos.json;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.JsonWriter;
import com.zappos.json.ZapposJson;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.IOException;
import java.io.PipedWriter;
import java.io.StringWriter;
import java.io.Writer;
import java.time.ZoneId;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonWriter_ESTest extends JsonWriter_ESTest_scaffolding {

    
    @Test
    public void testWriteMap() throws IOException {
        Map<String, Object> map = new HashMap<>();
        map.put("stringKey", "stringValue");
        map.put("booleanKey", true);
        map.put("numberKey", 123);
        ZapposJson zapposJson = new ZapposJson() {
            @Override
            public void toJson(Object value, Writer writer) {
                try {
                    if (value == null) {
                        writer.write("null");
                    } else if (value instanceof String) {
                        JsonWriter.writeString(this, (String) value, writer);
                    } else if (value instanceof Boolean) {
                        JsonWriter.writeBoolean(this, (Boolean) value, writer);
                    } else if (value instanceof Number) {
                        JsonWriter.writeNumber(this, (Number) value, writer);
                    } else {
                        JsonWriter.writeString(this, value.toString(), writer);
                    }
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        };
        java.io.StringWriter writer = new java.io.StringWriter();

        JsonWriter.writeMap(zapposJson, map, writer);

        String json = writer.toString();
        assert json.startsWith("{");
        assert json.endsWith("}");
        assert json.contains("\"stringKey\":\"stringValue\"");
        assert json.contains("\"booleanKey\":true");
        assert json.contains("\"numberKey\":123");
    }
}
