// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;









import com.zappos.json.WriterConfig;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {

    
    





    
@Test
public void testIs_WriterConfigFlagsReflectCorrectly() {
    // Arrange:
    // Create a subclass to access the private WRITER_CONFIGS array for testing
    class TestZapposJson extends ZapposJson {
        // Expose WRITER_CONFIGS for testing by returning reference
        boolean[] getWriterConfigs() {
            return WRITER_CONFIGS;
        }
        // Provide a method to set config flags for testing
        void setWriterConfigFlag(WriterConfig config, boolean value) {
            WRITER_CONFIGS[config.ordinal()] = value;
        }
    }
    TestZapposJson zapposJson = new TestZapposJson();

    // Initially all flags should be false
    for (WriterConfig config : WriterConfig.values()) {
        assertFalse(zapposJson.is(config), "Expected default config flag to be false for " + config);
    }

    // Act & Assert:
    // For each WriterConfig value, set to true and verify is() returns true
    for (WriterConfig config : WriterConfig.values()) {
        zapposJson.setWriterConfigFlag(config, true);
        assertTrue(zapposJson.is(config), "Expected config flag to be true for " + config);

        // Reset to false and verify is() returns false again
        zapposJson.setWriterConfigFlag(config, false);
        assertFalse(zapposJson.is(config), "Expected config flag to be false after reset for " + config);
    }
}
}
