// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;



import java.math.BigInteger;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {

    
    
    

@Test
public void testAddValueFormatter_ShouldRegisterValueFormatterForGivenType() {
    // Arrange:
    ZapposJson zapposJson = new ZapposJson();
    class DummyFormatter implements ValueFormatter<Object> {
        @Override
        public String format(Object value) {
            return "formatted";
        }
    }
    Class<?> targetClass = String.class;
    DummyFormatter formatter = new DummyFormatter();

    // Act:
    zapposJson.addValueFormatter(targetClass, formatter);

    // Assert:
    // Using reflection to access the protected VALUE_FORMATTERS map
    try {
        java.lang.reflect.Field field = ZapposJson.class.getDeclaredField("VALUE_FORMATTERS");
        field.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<Class<?>, ValueFormatter<Object>> map =
                (Map<Class<?>, ValueFormatter<Object>>) field.get(zapposJson);

        assertTrue(map.containsKey(targetClass), "VALUE_FORMATTERS should contain the target class as key");
        assertSame(formatter, map.get(targetClass), "The formatter registered should be the same instance as passed");
    } catch (NoSuchFieldException | IllegalAccessException e) {
        fail("Reflection failed: " + e.getMessage());
    }
}
}
