// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/FromTagData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:38:11 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class FromTagData_ESTest extends FromTagData_ESTest_scaffolding {
@Test
public void testSetFullName() {
    FromTagData fromTagData = new FromTagData();
    String testFullName = "John Doe";
    fromTagData.setFullName(testFullName);
    // Since there is no getFullName() method defined in the provided context, 
    // we will rely on toString() if it includes fullName, or else this test cannot verify directly.
    // Assuming toString() includes fullName for verification:
    String toStringResult = fromTagData.toString();
    assert toStringResult != null && toStringResult.contains(testFullName) : "Full name was not set correctly";
}
}
