// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/InstagramSubscription_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:59:46 GMT 2024
 */
package org.jinstagram.realtime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.jinstagram.realtime.InstagramSubscription;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramSubscription_ESTest extends InstagramSubscription_ESTest_scaffolding {
@Test
public void testObjectIdSetsValueAndReturnsInstance() {
    InstagramSubscription subscription = new InstagramSubscription();
    String testObjectId = "12345";

    InstagramSubscription returned = subscription.objectId(testObjectId);

    // Check that the returned instance is the same as the original (method chaining)
    org.junit.Assert.assertSame(subscription, returned);

    // Use toString or reflection to verify the internal params map contains the objectId
    // Since params is private and no getter is provided, we rely on toString output containing the objectId
    String toStringOutput = subscription.toString();
    org.junit.Assert.assertTrue("toString should contain the objectId",
            toStringOutput != null && toStringOutput.contains(testObjectId));
}
}
