// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
@Test
public void testDecodeAndAppendEntries() {
    Map<String, String> source = new HashMap<>();
    source.put("key 1", "value/1");
    source.put("key&2", "value 2");
    source.put("key+3", "value+3");

    Map<String, String> target = new HashMap<>();
    target.put("existingKey", "existingValue");

    MapUtils.decodeAndAppendEntries(source, target);

    // Expected keys and values after percent encoding
    // space -> %20, / -> %2F, & -> %26, + -> %2B
    Map<String, String> expected = new HashMap<>();
    expected.put("existingKey", "existingValue");
    expected.put("key%201", "value%2F1");
    expected.put("key%262", "value%202");
    expected.put("key%2B3", "value%2B3");

    // Assert that target contains all expected entries
    for (Map.Entry<String, String> entry : expected.entrySet()) {
        String actualValue = target.get(entry.getKey());
        org.junit.Assert.assertNotNull("Missing key: " + entry.getKey(), actualValue);
        org.junit.Assert.assertEquals("Value mismatch for key: " + entry.getKey(), entry.getValue(), actualValue);
    }
}
}
