// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentsFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:32:11 GMT 2024
 */
package org.jinstagram.entity.comments;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaCommentsFeed_ESTest extends MediaCommentsFeed_ESTest_scaffolding {
@Test
public void testToString() {
    MediaCommentsFeed feed = new MediaCommentsFeed();

    // Create and set Meta object
    Meta meta = new Meta();
    // Assuming Meta has a suitable toString or fields to set, otherwise just use default
    feed.setMeta(meta);

    // Create and set CommentData list
    CommentData comment1 = new CommentData();
    CommentData comment2 = new CommentData();
    List<CommentData> comments = List.of(comment1, comment2);
    feed.setCommentDataList(comments);

    String expected = String.format("MediaCommentsFeed [commentDataList=%s, meta=%s]", comments, meta);
    String actual = feed.toString();

    // Assert that toString returns the expected formatted string
    org.junit.Assert.assertEquals(expected, actual);
}
}
