// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Pagination_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:50:55 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Pagination;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Pagination_ESTest extends Pagination_ESTest_scaffolding {
@Test
public void testSetDepreciationWarning() {
    Pagination pagination = new Pagination();
    String warningMessage = "This feature is deprecated and will be removed soon.";
    pagination.setDepreciationWarning(warningMessage);
    // Since there is no getter for depreciationWarning in the provided context,
    // we rely on toString() to verify the value is set correctly.
    String toStringResult = pagination.toString();
    // Check that the toString output contains the warning message
    org.junit.Assert.assertTrue(toStringResult.contains(warningMessage));
}
}
