// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagMediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:16:28 GMT 2024
 */
package org.jinstagram.entity.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagMediaFeed_ESTest extends TagMediaFeed_ESTest_scaffolding {
@Test
public void testSetData() {
    TagMediaFeed tagMediaFeed = new TagMediaFeed();

    // Create a list of MediaFeedData objects
    List<MediaFeedData> mediaFeedDataList = new LinkedList<>();
    mediaFeedDataList.add(new MediaFeedData());
    mediaFeedDataList.add(new MediaFeedData());

    // Set the data list
    tagMediaFeed.setData(mediaFeedDataList);

    // Verify that the data list was set correctly
    List<MediaFeedData> retrievedData = tagMediaFeed.getData();
    org.junit.Assert.assertNotNull(retrievedData);
    org.junit.Assert.assertEquals(2, retrievedData.size());
    org.junit.Assert.assertSame(mediaFeedDataList, retrievedData);
}
}
