// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {
    





@Test
public void testRemoveRepeatedCharacters() {
    // Arrange
    Line line = new Line();
    line.addTextChunk(new TextChunkMock("aaaaa"));  // TextChunk with consecutive 'a's
    line.addTextChunk(new TextChunkMock("bb"));     // TextChunk with 'b's
    line.addTextChunk(new TextChunkMock("cccc"));   // TextChunk with consecutive 'c's
    Character c = 'a';
    int minRunLength = 2;

    // Act
    Line result = Line.removeRepeatedCharacters(line, c, minRunLength);

    // Assert
    assertEquals(2, result.getTextElements().size());  // Two TextChunks expected after removal
    assertEquals("bb", result.getTextElements().get(0).getText());  // 'b's TextChunk should remain unchanged
    assertEquals("cc", result.getTextElements().get(1).getText());  // 'c's TextChunk should have consecutive chars removed
}
}
