// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    @Test
    public void testIsSameChar() {
        // Create a TextElement for testing
        TextElement textElement = new TextElement(0, 0, 10, 10, "Hello");

        // Create a TextChunk with the TextElement
        TextChunk textChunk = new TextChunk(textElement);

        // Define the array of characters to compare
        Character[] charsToCompare = {'H', 'e', 'l', 'o'};

        // Test if the TextChunk contains all characters in the array
        assertTrue(textChunk.isSameChar(charsToCompare));

        // Define another array of characters to compare
        Character[] charsToCompare2 = {'H', 'e', 'l', 'o', '!'};

        // Test if the TextChunk contains all characters in the second array
        assertFalse(textChunk.isSameChar(charsToCompare2));
    }
}
