// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/BasicExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:49:38 GMT 2024
 */
package technology.tabula.extractors;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Page;
import technology.tabula.Ruling;
import technology.tabula.TextChunk;
import technology.tabula.extractors.BasicExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class BasicExtractionAlgorithm_ESTest extends BasicExtractionAlgorithm_ESTest_scaffolding {
    






@Test
public void testColumnPositions() {
    // Arrange
    List<Line> lines = new ArrayList<>();
    Line line1 = new Line();
    line1.addTextChunk(new TextChunk(10, 20)); // Sample text chunk for testing
    line1.addTextChunk(new TextChunk(30, 40)); // Sample text chunk for testing
    lines.add(line1);

    Line line2 = new Line();
    line2.addTextChunk(new TextChunk(15, 25)); // Sample text chunk for testing
    line2.addTextChunk(new TextChunk(35, 45)); // Sample text chunk for testing
    lines.add(line2);

    // Act
    List<Float> result = BasicExtractionAlgorithm.columnPositions(lines);

    // Assert
    Collections.sort(result); // Sort the result list
    assertEquals(20.0f, result.get(0)); // Assert the first rightmost position
    assertEquals(40.0f, result.get(1)); // Assert the second rightmost position
}
}
