// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Images_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:42:55 GMT 2024
 */
package org.jinstagram.entity.common;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.ImageData;
import org.jinstagram.entity.common.Images;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Images_ESTest extends Images_ESTest_scaffolding {
    
@Test
public void testToString() {
    // The test is meant to verify that the toString() method of the Images class correctly formats and returns a string representation of the Images object with its low resolution, standard resolution, and thumbnail image data.

    // Arrange
    Images images = new Images();
    ImageData lowResolution = new ImageData();
    ImageData standardResolution = new ImageData();
    ImageData thumbnail = new ImageData();

    images.setLowResolution(lowResolution);
    images.setStandardResolution(standardResolution);
    images.setThumbnail(thumbnail);

    // Act
    String result = images.toString();

    // Assert
    String expected = "Images [lowResolution=" + lowResolution + ", standardResolution=" + standardResolution + ", thumbnail=" + thumbnail + "]";
    assertEquals(expected, result);
}
}
