// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/locations/LocationSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:03:11 GMT 2024
 */
package org.jinstagram.entity.locations;


import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import org.jinstagram.entity.common.LocationSearchFeed;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Location;
import org.jinstagram.entity.locations.LocationSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LocationSearchFeed_ESTest extends LocationSearchFeed_ESTest_scaffolding {
    





@Test
public void testSetLocationList() {
    // Arrange
    LocationSearchFeed locationSearchFeed = new LocationSearchFeed();
    List<Location> testLocations = new ArrayList<>();
    Location location1 = new Location();
    location1.setId("1");
    location1.setName("Location 1");
    location1.setLatitude(40.7128);
    location1.setLongitude(74.0060);
    testLocations.add(location1);

    // Act
    locationSearchFeed.setLocationList(testLocations);

    // Assert
    assertEquals(testLocations, locationSearchFeed.getLocationList());
}
}
