// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/locations/LocationSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:03:11 GMT 2024
 */
package org.jinstagram.entity.locations;
Your import statements here.




import com.google.gson.annotations.SerializedName;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Location;
import org.jinstagram.entity.locations.LocationSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LocationSearchFeed_ESTest extends LocationSearchFeed_ESTest_scaffolding {
    





    
@Test
public void testToStringMethod() {
    // The test is meant to verify that the toString() method in the LocationSearchFeed class correctly formats and returns a string representation that includes the list of locations.

    // Arrange
    Location location1 = new Location("City A");
    Location location2 = new Location("City B");
    List<Location> locationList = new ArrayList<>();
    locationList.add(location1);
    locationList.add(location2);
    LocationSearchFeed locationSearchFeed = new LocationSearchFeed();
    locationSearchFeed.setLocationList(locationList);
    
    // Act
    String result = locationSearchFeed.toString();
    
    // Assert
    assertEquals("LocationSearchFeed [locationList=[Location{city='City A'}, Location{city='City B'}]]", result);
}
}
