// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/Preconditions_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:17:41 GMT 2024
 */
package org.jinstagram.utils;
import static org.mockito.Mockito.*;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.jinstagram.utils.Preconditions;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.Preconditions;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Preconditions_ESTest extends Preconditions_ESTest_scaffolding {
    
@Test
public void testCheckValidRadius_WhenRadiusStringIsEmpty_ShouldThrowIllegalArgumentException() {
    // Arrange
    String radiusString = "";
    String errorMsg = "Invalid radius";
    
    // Act & Assert
    try {
        Preconditions.checkValidRadius(radiusString, errorMsg);
        fail("Expected IllegalArgumentException to be thrown");
    } catch (IllegalArgumentException e) {
        assertEquals(errorMsg, e.getMessage());
    }
}
}
