// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagMediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:16:28 GMT 2024
 */
package org.jinstagram.entity.tags;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.LinkedList;
import java.util.List;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagMediaFeed_ESTest extends TagMediaFeed_ESTest_scaffolding {


    
    
@Test
public void testGetPagination() {
    TagMediaFeed tagMediaFeed = new TagMediaFeed();
    Pagination pagination = new Pagination();

    tagMediaFeed.setPagination(pagination);

    assertEquals(pagination, tagMediaFeed.getPagination());
}


    
    @Test
    public void testSetMeta() {
        // Given
        Meta testMeta = new Meta();
        TagMediaFeed tagMediaFeed = new TagMediaFeed();

        // When
        tagMediaFeed.setMeta(testMeta);

        // Then
        assertEquals(testMeta, tagMediaFeed.getMeta());
    }


    
@Test
public void testSetData() {
    TagMediaFeed tagMediaFeed = new TagMediaFeed();

    List<MediaFeedData> testData = new LinkedList<MediaFeedData>();

    MediaFeedData mediaFeedData1 = new MediaFeedData();
    MediaFeedData mediaFeedData2 = new MediaFeedData();
    testData.add(mediaFeedData1);
    testData.add(mediaFeedData2);
    tagMediaFeed.setData(testData);
    List<MediaFeedData> retrievedData = tagMediaFeed.getData();
    assertEquals(testData, retrievedData);
}


    
    @Test
    public void testSetMeta_1() {
        // Given
        Meta meta = new Meta();
        TagMediaFeed tagMediaFeed = new TagMediaFeed();

        // When
        tagMediaFeed.setMeta(meta);

        // Then
        assertEquals(meta, tagMediaFeed.getMeta());
    }

}
