// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/BigDecimalFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:31:38 GMT 2024
 */
package com.zappos.json.format;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.math.BigDecimal;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.BigDecimalFormatter;
import com.zappos.json.format.ValueFormatter;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class BigDecimalFormatter_ESTest extends BigDecimalFormatter_ESTest_scaffolding {
    @Test
    public void testCast() {
        BigDecimalFormatter bigDecimalFormatter = new BigDecimalFormatter();
        
        // Test case 1: Valid input object
        Object validObject = new BigDecimal("10.5");
        BigDecimal result1 = bigDecimalFormatter.cast(validObject);
        assertEquals(new BigDecimal("10.5"), result1);
        
        // Test case 2: Invalid input object (String)
        Object invalidObject = "invalid";
        try {
            BigDecimal result2 = bigDecimalFormatter.cast(invalidObject);
            // The test should not reach this point if the method throws a ClassCastException
        } catch (ClassCastException e) {
            // Expected behavior
        }
        
        // Additional test cases can be added as needed
    }
}
