// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.lang.reflect.Field;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetField() {
        try {
            // Test case 1: Field exists in the given class
            Field field1 = Reflections.getField(TestClass.class, "field1");
            assertNotNull(field1);
            assertEquals("field1", field1.getName());
            
            // Test case 2: Field exists in a superclass
            Field field2 = Reflections.getField(TestSubclass.class, "field1");
            assertNotNull(field2);
            assertEquals("field1", field2.getName());
            
            // Test case 3: Field does not exist in the class hierarchy
            Field field3 = Reflections.getField(TestClass.class, "nonExistentField");
            assertNull(field3);
            
        } catch (NoSuchFieldException e) {
            fail("Field not found");
        }
    }
}
