// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/BigIntegerFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:33:42 GMT 2024
 */
package com.zappos.json.format;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.BigIntegerFormatter;
import com.zappos.json.format.ValueFormatter;
import java.math.BigInteger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class BigIntegerFormatter_ESTest extends BigIntegerFormatter_ESTest_scaffolding {
@Test
public void testCast() {
    BigIntegerFormatter formatter = new BigIntegerFormatter();

    // Test casting a valid BigInteger object
    BigInteger bigInt = BigInteger.valueOf(12345L);
    BigInteger result = formatter.cast(bigInt);
    org.junit.Assert.assertEquals(bigInt, result);

    // Test casting a null object (should return null)
    Object nullObj = null;
    BigInteger nullResult = formatter.cast(nullObj);
    org.junit.Assert.assertNull(nullResult);

    // Test casting an invalid type should throw ClassCastException
    Object notBigInt = "not a BigInteger";
    try {
        formatter.cast(notBigInt);
        org.junit.Assert.fail("Expected ClassCastException was not thrown");
    } catch (ClassCastException e) {
        // expected exception
    }
}
}
