// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;






import java.math.BigDecimal;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {



    
    
    
    
    @Test
    void testRemoveValueFormatter() {
        ZapposJson zapposJson = new ZapposJson();

        // Add a formatter for Date class and verify it is present
        ValueFormatter<Object> originalFormatter = zapposJson.VALUE_FORMATTERS.get(Date.class);
        assertNotNull(originalFormatter, "Formatter for Date should be present initially");

        // Remove the formatter for Date class
        zapposJson.removeValueFormatter(Date.class);

        // Verify the formatter for Date class is removed
        assertNull(zapposJson.VALUE_FORMATTERS.get(Date.class), "Formatter for Date should be removed");

        // Remove a formatter for a class that was never added (e.g., BigDecimal)
        assertNotNull(zapposJson.VALUE_FORMATTERS.get(BigDecimal.class), "Formatter for BigDecimal should be present initially");
        zapposJson.removeValueFormatter(BigDecimal.class);
        assertNull(zapposJson.VALUE_FORMATTERS.get(BigDecimal.class), "Formatter for BigDecimal should be removed");

        // Remove a formatter for a class that does not exist in the map (e.g., String.class)
        assertNull(zapposJson.VALUE_FORMATTERS.get(String.class), "Formatter for String should not be present initially");
        // Should not throw any exception
        zapposJson.removeValueFormatter(String.class);
        assertNull(zapposJson.VALUE_FORMATTERS.get(String.class), "Formatter for String should still not be present");
    }
}
