// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;





import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {



    
    
    
    @Test
    public void testToString_withMultipleTextChunks() {
        List<TextChunk> chunks = new ArrayList<>();
        chunks.add(new TextChunk("Hello"));
        chunks.add(new TextChunk("World"));
        chunks.add(new TextChunk("!"));

        TestLine line = new TestLine(chunks);
        String result = line.toString();

        // The result should start with the superclass toString() without the last ']'
        String superString = superToString(line);
        assertTrue(result.startsWith(superString.substring(0, superString.length() - 1)));

        // The result should contain the chunks label
        assertTrue(result.contains(",chunks="));

        // The result should contain each chunk text quoted and separated by comma and space
        assertTrue(result.contains("'Hello'"));
        assertTrue(result.contains("'World'"));
        assertTrue(result.contains("'!'"));

        // The result should end with a closing bracket ']'
        assertTrue(result.endsWith("]"));

        // The chunks should be separated by comma and space
        assertTrue(result.contains("'Hello', 'World', '!'" ) || result.contains("'Hello', 'World', '!'" ));
    }
}
