// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.WriterConfig;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {
    
    
    
    
    
    
    
    @Test
    public void testIs() {
        ZapposJson zapposJson = new ZapposJson();
        
        // Test for default WriterConfig values
        for (WriterConfig config : WriterConfig.values()) {
            assertFalse(zapposJson.is(config));
        }
        
        // Enable a specific WriterConfig and check if it returns true
        zapposJson.WRITER_CONFIGS[WriterConfig.INDENT_OUTPUT.ordinal()] = true;
        assertTrue(zapposJson.is(WriterConfig.INDENT_OUTPUT));
        
        // Disable the previously enabled WriterConfig and check if it returns false
        zapposJson.WRITER_CONFIGS[WriterConfig.INDENT_OUTPUT.ordinal()] = false;
        assertFalse(zapposJson.is(WriterConfig.INDENT_OUTPUT));
    }
}
