// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/wrapper/ArrayTypeWrapper_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:16:56 GMT 2024
 */
package com.zappos.json.wrapper;


import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.wrapper.ArrayTypeWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.wrapper.ArrayTypeWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ArrayTypeWrapper_ESTest extends ArrayTypeWrapper_ESTest_scaffolding {


    

    @Test
    public void testSetTarget_SetsTargetCorrectly() throws NoSuchFieldException, IllegalAccessException {
        ArrayTypeWrapper<String> wrapper = new ArrayTypeWrapper<>();
        String expectedTarget = "testTarget";
        wrapper.setTarget(expectedTarget);

        java.lang.reflect.Field targetField = ArrayTypeWrapper.class.getDeclaredField("target");
        targetField.setAccessible(true);
        Object actualTarget = targetField.get(wrapper);

        assertEquals(expectedTarget, actualTarget);
    }


    
@Test
public void testSetComponentType() {
    // Arrange:
    ArrayTypeWrapper wrapper = new ArrayTypeWrapper();
    Class<?> expectedClass = String.class;

    // Act:
    wrapper.setComponentType(expectedClass);

    // Assert:
    // Since componentType is private and no getter is provided,
    // we need to verify it via reflection.
    try {
        java.lang.reflect.Field field = ArrayTypeWrapper.class.getDeclaredField("componentType");
        field.setAccessible(true);
        Object actual = field.get(wrapper);
        assertEquals(expectedClass, actual);
    } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new RuntimeException(e);
    }
}


    
@Test
public void testSetComponentType_1() {
    // Arrange:
    ArrayTypeWrapper wrapper = new ArrayTypeWrapper();
    Class<?> expectedType = String.class;
    
    // Act:
    wrapper.setComponentType(expectedType);
    
    // Assert:
    // Since componentType is private and no getter is provided,
    // we will use reflection to verify that the field was set correctly.
    try {
        java.lang.reflect.Field field = ArrayTypeWrapper.class.getDeclaredField("componentType");
        field.setAccessible(true);
        Class<?> actualType = (Class<?>) field.get(wrapper);
        assertEquals(expectedType, actualType);
    } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new RuntimeException(e);
    }
}


    
    

@Test
public void testSetTarget_ShouldUpdateTargetField() {
    // Arrange:
    ArrayTypeWrapper<String> wrapper = new ArrayTypeWrapper<>();
    String expectedTarget = "testValue";

    // Act:
    wrapper.setTarget(expectedTarget);

    // Assert:
    // Since 'target' is private and no getter is defined,
    // we use reflection to access the private field and verify its value.
    try {
        java.lang.reflect.Field targetField = ArrayTypeWrapper.class.getDeclaredField("target");
        targetField.setAccessible(true);
        Object actualTarget = targetField.get(wrapper);
        assertEquals(expectedTarget, actualTarget);
    } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new RuntimeException(e);
    }
}

}
