// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonWriterCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:02:58 GMT 2024
 */
package com.zappos.json;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonWriterCodeGenerator;
import com.zappos.json.JsonWriterInvoker;
import com.zappos.json.ZapposJson;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonWriterCodeGenerator_ESTest extends JsonWriterCodeGenerator_ESTest_scaffolding {
@Test
public void testDeregisterRemovesWriterInvoker() throws Exception {
    ZapposJson zapposJson = new ZapposJson();
    JsonBeanIntrospector beanIntrospector = new JsonBeanIntrospector();
    JsonWriterCodeGenerator generator = new JsonWriterCodeGenerator(zapposJson, beanIntrospector);

    // Use a sample class for registration and deregistration
    Class<?> clazz = String.class;

    // Register a writer for the class to ensure it exists in the map
    JsonWriterInvoker invoker = generator.registerWriter(clazz);
    // Confirm the writer is registered (getWriter should return non-null)
    JsonWriterInvoker registeredInvoker = generator.getWriter(clazz);
    org.junit.Assert.assertNotNull("WriterInvoker should be registered", registeredInvoker);

    // Call deregister to remove the writer
    generator.deregister(clazz);

    // After deregister, getWriter should return null
    JsonWriterInvoker afterDeregisterInvoker = generator.getWriter(clazz);
    org.junit.Assert.assertNull("WriterInvoker should be removed after deregister", afterDeregisterInvoker);
}
}
