// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/ObjectArray_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {
@Test
public void testToArrayWithProvidedArray() {
    ObjectArray array = new ObjectArray();
    array.add("one");
    array.add("two");
    array.add("three");

    // Provide an array of the same type and size smaller than the ObjectArray size
    String[] input = new String[2];
    String[] result = array.toArray(input);

    // The returned array should be of type String[] and length equal to ObjectArray size
    org.junit.Assert.assertEquals(3, result.length);
    org.junit.Assert.assertArrayEquals(new String[]{"one", "two", "three"}, result);

    // Provide an array of the same type and size equal to ObjectArray size
    String[] inputExact = new String[3];
    String[] resultExact = array.toArray(inputExact);
    org.junit.Assert.assertSame(inputExact, resultExact);
    org.junit.Assert.assertArrayEquals(new String[]{"one", "two", "three"}, resultExact);

    // Provide an array of the same type and size larger than ObjectArray size
    String[] inputLarger = new String[5];
    String[] resultLarger = array.toArray(inputLarger);
    org.junit.Assert.assertSame(inputLarger, resultLarger);
    org.junit.Assert.assertArrayEquals(new String[]{"one", "two", "three", null, null}, resultLarger);
}
}
