// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
@Test
public void testGetGenericParameterTypes() throws NoSuchMethodException {
    class TestClass {
        public void methodWithGenericParam(java.util.Map<String, Integer> map) {}
        public void methodWithNonGenericParam(String s) {}
        public void methodWithMultipleParams(int i, java.util.List<Double> list) {}
        public void methodWithNestedGeneric(java.util.Map<String, java.util.List<Integer>> map) {}
    }

    // Method with a single generic parameter Map<String, Integer>
    Method method1 = TestClass.class.getMethod("methodWithGenericParam", java.util.Map.class);
    Class<?>[] genericTypes1 = Reflections.getGenericParameterTypes(method1);
    // Expecting [String.class, Integer.class]
    org.junit.Assert.assertNotNull(genericTypes1);
    org.junit.Assert.assertArrayEquals(new Class<?>[]{String.class, Integer.class}, genericTypes1);

    // Method with a single non-generic parameter String
    Method method2 = TestClass.class.getMethod("methodWithNonGenericParam", String.class);
    Class<?>[] genericTypes2 = Reflections.getGenericParameterTypes(method2);
    // Expecting null because no generic parameter
    org.junit.Assert.assertNull(genericTypes2);

    // Method with multiple parameters: int and List<Double>
    Method method3 = TestClass.class.getMethod("methodWithMultipleParams", int.class, java.util.List.class);
    Class<?>[] genericTypes3 = Reflections.getGenericParameterTypes(method3);
    // The first generic parameter is List<Double> (second parameter), but method returns first generic parameter only
    // According to the method, it returns the first generic parameter it finds in the parameter list, so it should find List<Double>
    // But the first parameter is int (non-generic), second is List<Double> (generic)
    // The method loops over parameters in order, so it should return the generic types of List<Double> => [Double.class]
    org.junit.Assert.assertNotNull(genericTypes3);
    org.junit.Assert.assertArrayEquals(new Class<?>[]{Double.class}, genericTypes3);

    // Method with nested generic parameter Map<String, List<Integer>>
    Method method4 = TestClass.class.getMethod("methodWithNestedGeneric", java.util.Map.class);
    Class<?>[] genericTypes4 = Reflections.getGenericParameterTypes(method4);
    // The method only returns the first level generic parameters, so expecting [String.class, List.class]
    org.junit.Assert.assertNotNull(genericTypes4);
    org.junit.Assert.assertEquals(2, genericTypes4.length);
    org.junit.Assert.assertEquals(String.class, genericTypes4[0]);
    org.junit.Assert.assertEquals(java.util.List.class, genericTypes4[1]);
}
}
