// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {
@Test
public void testToJson_variousTypes() throws Exception {
    ZapposJson zapposJson = ZapposJson.getInstance();

    // Use StringWriter to capture output
    java.io.StringWriter writer = new java.io.StringWriter();

    // Test null
    writer.getBuffer().setLength(0);
    zapposJson.toJson(null, writer);
    org.junit.Assert.assertEquals("null", writer.toString());

    // Test Boolean
    writer.getBuffer().setLength(0);
    zapposJson.toJson(Boolean.TRUE, writer);
    org.junit.Assert.assertEquals("true", writer.toString());

    // Test String
    writer.getBuffer().setLength(0);
    zapposJson.toJson("testString", writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("\""));
    org.junit.Assert.assertTrue(writer.toString().endsWith("\""));

    // Test Character
    writer.getBuffer().setLength(0);
    zapposJson.toJson('c', writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("\""));
    org.junit.Assert.assertTrue(writer.toString().endsWith("\""));

    // Test Number (Integer)
    writer.getBuffer().setLength(0);
    zapposJson.toJson(123, writer);
    org.junit.Assert.assertEquals("123", writer.toString());

    // Test Enum
    writer.getBuffer().setLength(0);
    enum TestEnum { A, B }
    zapposJson.toJson(TestEnum.A, writer);
    org.junit.Assert.assertTrue(writer.toString().contains("A"));

    // Test Iterable (List)
    writer.getBuffer().setLength(0);
    java.util.List<Integer> list = java.util.Arrays.asList(1, 2, 3);
    zapposJson.toJson(list, writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("["));
    org.junit.Assert.assertTrue(writer.toString().endsWith("]"));

    // Test Map
    writer.getBuffer().setLength(0);
    java.util.Map<String, Integer> map = new java.util.HashMap<>();
    map.put("key", 42);
    zapposJson.toJson(map, writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("{"));
    org.junit.Assert.assertTrue(writer.toString().endsWith("}"));

    // Test array of primitives (int[])
    writer.getBuffer().setLength(0);
    int[] intArray = new int[] {1, 2, 3};
    zapposJson.toJson(intArray, writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("["));
    org.junit.Assert.assertTrue(writer.toString().endsWith("]"));

    // Test array of Objects (String[])
    writer.getBuffer().setLength(0);
    String[] strArray = new String[] {"a", "b"};
    zapposJson.toJson(strArray, writer);
    org.junit.Assert.assertTrue(writer.toString().startsWith("["));
    org.junit.Assert.assertTrue(writer.toString().endsWith("]"));

    // Test object with registered ValueFormatter (Date)
    writer.getBuffer().setLength(0);
    java.util.Date date = new java.util.Date(0);
    zapposJson.toJson(date, writer);
    String dateJson = writer.toString();
    org.junit.Assert.assertFalse(dateJson.isEmpty());

    // Test user-defined object (simple POJO)
    writer.getBuffer().setLength(0);
    class Person {
        public String name = "John";
        public int age = 30;
    }
    Person person = new Person();
    zapposJson.toJson(person, writer);
    String json = writer.toString();
    org.junit.Assert.assertTrue(json.contains("name"));
    org.junit.Assert.assertTrue(json.contains("age"));
}
}
