// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:18:36 GMT 2024
 */
package org.jinstagram.auth.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OAuthConfig_ESTest extends OAuthConfig_ESTest_scaffolding {
@Test
public void testHasScope() {
    // Case 1: OAuthConfig created without scope (using 2-arg constructor)
    OAuthConfig config1 = new OAuthConfig("key", "secret");
    assert !config1.hasScope() : "Expected hasScope() to be false when scope is not set";

    // Case 2: OAuthConfig created with null scope explicitly
    OAuthConfig config2 = new OAuthConfig("key", "secret", "callback", null);
    assert !config2.hasScope() : "Expected hasScope() to be false when scope is null";

    // Case 3: OAuthConfig created with non-null scope
    OAuthConfig config3 = new OAuthConfig("key", "secret", "callback", "read");
    assert config3.hasScope() : "Expected hasScope() to be true when scope is set";
}
}
