// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Caption_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:34:16 GMT 2024
 */
package org.jinstagram.entity.common;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Caption;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Caption_ESTest extends Caption_ESTest_scaffolding {
    
    
@Test
public void testSetCreatedTime() {
    Caption caption = new Caption();
    String testTime = "2024-06-01T12:00:00Z";
    caption.setCreatedTime(testTime);
    try {
        java.lang.reflect.Field field = Caption.class.getDeclaredField("createdTime");
        field.setAccessible(true);
        String actual = (String) field.get(caption);
        assertEquals(testTime, actual);
    } catch (NoSuchFieldException e) {
        fail("Reflection failed: " + e.getMessage());
    } catch (IllegalAccessException e) {
        fail("Reflection failed: " + e.getMessage());
    }
    caption.setCreatedTime(null);
    try {
        java.lang.reflect.Field field = Caption.class.getDeclaredField("createdTime");
        field.setAccessible(true);
        String actual = (String) field.get(caption);
        assertNull(actual);
    } catch (NoSuchFieldException e) {
        fail("Reflection failed: " + e.getMessage());
    } catch (IllegalAccessException e) {
        fail("Reflection failed: " + e.getMessage());
    }
    caption.setCreatedTime("");
    try {
        java.lang.reflect.Field field = Caption.class.getDeclaredField("createdTime");
        field.setAccessible(true);
        String actual = (String) field.get(caption);
        assertEquals("", actual);
    } catch (NoSuchFieldException e) {
        fail("Reflection failed: " + e.getMessage());
    } catch (IllegalAccessException e) {
        fail("Reflection failed: " + e.getMessage());
    }
}
}
