// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/Counts_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:20:16 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.basicinfo.Counts;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Counts_ESTest extends Counts_ESTest_scaffolding {
    
    

@Test
public void testSetMedia() {
    Counts counts = new Counts();
    counts.setMedia(10);

    assertEquals("The media field should be set to 10", 10, counts.getMedia());

    counts.setMedia(-5);
    assertEquals("The media field should be set to -5", -5, counts.getMedia());
    counts.setMedia(0);
    assertEquals("The media field should be set to 0", 0, counts.getMedia());
}
}
