// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/comments/MediaCommentsFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:32:11 GMT 2024
 */
package org.jinstagram.entity.comments;




import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.comments.MediaCommentsFeed;
import org.jinstagram.entity.common.Meta;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaCommentsFeed_ESTest extends MediaCommentsFeed_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testSetCommentDataList() {
        MediaCommentsFeed mediaCommentsFeed = new MediaCommentsFeed();

        // Initially, commentDataList should be null or empty
        assertNull(getCommentDataList(mediaCommentsFeed), "Initial commentDataList should be null");

        // Create a list of CommentData objects
        List<CommentData> commentList = new ArrayList<>();

        CommentData comment1 = new CommentData() {
            private String id = "1";
            private String text = "First comment";
            private String createdTime = "1234567890";
            private FromTagData from = null;

            @Override
            public String getCreatedTime() { return createdTime; }
            @Override
            public void setCreatedTime(String createdTime) { this.createdTime = createdTime; }
            @Override
            public String getText() { return text; }
            @Override
            public void setText(String text) { this.text = text; }
            @Override
            public FromTagData getCommentFrom() { return from; }
            @Override
            public void setCommentFrom(FromTagData commentFrom) { this.from = commentFrom; }
            @Override
            public String getId() { return id; }
            @Override
            public void setId(String id) { this.id = id; }
            @Override
            public String toString() { return "CommentData{id='" + id + "', text='" + text + "'}"; }
        };

        CommentData comment2 = new CommentData() {
            private String id = "2";
            private String text = "Second comment";
            private String createdTime = "0987654321";
            private FromTagData from = null;

            @Override
            public String getCreatedTime() { return createdTime; }
            @Override
            public void setCreatedTime(String createdTime) { this.createdTime = createdTime; }
            @Override
            public String getText() { return text; }
            @Override
            public void setText(String text) { this.text = text; }
            @Override
            public FromTagData getCommentFrom() { return from; }
            @Override
            public void setCommentFrom(FromTagData commentFrom) { this.from = commentFrom; }
            @Override
            public String getId() { return id; }
            @Override
            public void setId(String id) { this.id = id; }
            @Override
            public String toString() { return "CommentData{id='" + id + "', text='" + text + "'}"; }
        };

        commentList.add(comment1);
        commentList.add(comment2);

        // Set the commentDataList
        mediaCommentsFeed.setCommentDataList(commentList);

        // Verify that the internal list is updated correctly
        List<CommentData> internalList = getCommentDataList(mediaCommentsFeed);
        assertNotNull(internalList, "commentDataList should not be null after setting");
        assertEquals(2, internalList.size(), "commentDataList size should be 2");
        assertEquals("1", internalList.get(0).getId(), "First comment id should be '1'");
        assertEquals("First comment", internalList.get(0).getText(), "First comment text mismatch");
        assertEquals("2", internalList.get(1).getId(), "Second comment id should be '2'");
        assertEquals("Second comment", internalList.get(1).getText(), "Second comment text mismatch");

        // Test replacing the list with a new list
        List<CommentData> newCommentList = new ArrayList<>();
        CommentData comment3 = new CommentData() {
            private String id = "3";
            private String text = "Third comment";
            @Override public String getCreatedTime() { return null; }
            @Override public void setCreatedTime(String createdTime) {}
            @Override public String getText() { return text; }
            @Override public void setText(String text) { this.text = text; }
            @Override public FromTagData getCommentFrom() { return null; }
            @Override public void setCommentFrom(FromTagData commentFrom) {}
            @Override public String getId() { return id; }
            @Override public void setId(String id) { this.id = id; }
            @Override public String toString() { return "CommentData{id='" + id + "', text='" + text + "'}"; }
        };
        newCommentList.add(comment3);

        mediaCommentsFeed.setCommentDataList(newCommentList);

        internalList = getCommentDataList(mediaCommentsFeed);
        assertNotNull(internalList, "commentDataList should not be null after resetting");
        assertEquals(1, internalList.size(), "commentDataList size should be 1 after resetting");
        assertEquals("3", internalList.get(0).getId(), "Comment id should be '3' after resetting");
        assertEquals("Third comment", internalList.get(0).getText(), "Comment text mismatch after resetting");

        // Test setting null list
        mediaCommentsFeed.setCommentDataList(null);
        internalList = getCommentDataList(mediaCommentsFeed);
        assertNull(internalList, "commentDataList should be null after setting null");
    }
}
