// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/UserInfoData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:24:13 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.basicinfo.Counts;
import org.jinstagram.entity.users.basicinfo.UserInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserInfoData_ESTest extends UserInfoData_ESTest_scaffolding {
    
    



@Test
public void testSetBusiness() {
    UserInfoData userInfo = new UserInfoData();
    try {
        java.lang.reflect.Field field = UserInfoData.class.getDeclaredField("isBusiness");
        field.setAccessible(true);
        boolean initialValue = field.getBoolean(userInfo);

        Assert.assertEquals(false, initialValue, "Initial isBusiness value should be false");

        userInfo.setBusiness(true);
        boolean updatedValue = field.getBoolean(userInfo);
        Assert.assertEquals(true, updatedValue, "isBusiness should be true after setBusiness(true)");
        userInfo.setBusiness(false);
        boolean updatedValue2 = field.getBoolean(userInfo);
        Assert.assertEquals(false, updatedValue2, "isBusiness should be false after setBusiness(false)");
    } catch (NoSuchFieldException e) {
        throw new RuntimeException(e);
    } catch (IllegalAccessException e) {
        throw new RuntimeException(e);
    }
}
}
