// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/UserInfoData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:24:13 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.basicinfo.Counts;
import org.jinstagram.entity.users.basicinfo.UserInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserInfoData_ESTest extends UserInfoData_ESTest_scaffolding {
    
    

@Test
public void testToString() {
    UserInfoData userInfo = new UserInfoData();
    userInfo.setBio("Sample bio");
    Counts counts = new Counts();
    userInfo.setCounts(counts);
    userInfo.setFirstName("John");
    userInfo.setId("12345");

    userInfo.setLast_name("Doe");

    userInfo.setProfilePicture("http://example.com/pic.jpg");
    userInfo.setUsername("johndoe");
    userInfo.setFullName("John Doe");
    userInfo.setWebsite("http://example.com");
    userInfo.setBusiness(true);
    String expected = String.format(
        "UserInfoData [bio=%s, counts=%s, first_name=%s, id=%s, last_name=%s, profile_picture=%s, username=%s, fullName=%s, website=%s, isBusiness=%b]",
        "Sample bio", counts, "John", "12345", "Doe", "http://example.com/pic.jpg", "johndoe", "John Doe", "http://example.com", true);
    assertEquals(expected, userInfo.toString());
}
}
