// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Videos_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:57:54 GMT 2024
 */
package org.jinstagram.entity.common;


import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.VideoData;
import org.jinstagram.entity.common.Videos;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Videos_ESTest extends Videos_ESTest_scaffolding {
    
    

@Test
public void testToString() {
    VideoData lowRes = new VideoData();
    lowRes.setUrl("lowUrl");
    lowRes.setWidth(320);
    lowRes.setHeight(240);
    VideoData standardRes = new VideoData();
    standardRes.setUrl("standardUrl");
    standardRes.setWidth(640);
    standardRes.setHeight(480);
    Videos videos = new Videos();

    videos.setLowResolution(lowRes);

    videos.setStandardResolution(standardRes);
    String expected = String.format("Videos [lowResolution=%s, standardResolution=%s]", lowRes, standardRes);
    assertEquals(expected, videos.toString());
    Videos videosNull = new Videos();
    videosNull.setLowResolution(null);
    videosNull.setStandardResolution(null);
    String expectedNull = "Videos [lowResolution=null, standardResolution=null]";
    assertEquals(expectedNull, videosNull.toString());
}
}
