// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/BasicExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:49:38 GMT 2024
 */
package technology.tabula.extractors;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Page;
import technology.tabula.Ruling;
import technology.tabula.TextChunk;
import technology.tabula.extractors.BasicExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class BasicExtractionAlgorithm_ESTest extends BasicExtractionAlgorithm_ESTest_scaffolding {
    


    
    
    @Test
    public void testColumnPositions() {
        // Create sample lines for testing
        Line line1 = new Line();
        line1.addTextElement(new TextChunk(10, 20)); // Sample text element for line 1
        Line line2 = new Line();
        line2.addTextElement(new TextChunk(15, 25)); // Sample text element for line 2
        Line line3 = new Line();
        line3.addTextElement(new TextChunk(30, 40)); // Sample text element for line 3

        List<Line> lines = new ArrayList<>();
        lines.add(line1);
        lines.add(line2);
        lines.add(line3);

        List<Float> columnPositions = BasicExtractionAlgorithm.columnPositions(lines);

        // Assert the expected column positions based on the sample text elements
        assertEquals(20.0f, columnPositions.get(0)); // Expected rightmost position for column 1
        assertEquals(25.0f, columnPositions.get(1)); // Expected rightmost position for column 2
        assertEquals(40.0f, columnPositions.get(2)); // Expected rightmost position for column 3
    }
}
