// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/InstagramSubscription_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:59:46 GMT 2024
 */
package org.jinstagram.realtime;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.jinstagram.realtime.InstagramSubscription;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramSubscription_ESTest extends InstagramSubscription_ESTest_scaffolding {
    
    

    
    
    @Test
    public void testAspect_withValidAspect_shouldSetAspectAndReturnThis() {
        InstagramSubscription subscription = new InstagramSubscription();
        String validAspect = "media";

        InstagramSubscription returned = subscription.aspect(validAspect);

        assertSame(subscription, returned, "aspect() should return the same InstagramSubscription instance for chaining");
        assertEquals(validAspect, subscription.params.get(Constants.ASPECT), "The aspect parameter should be set correctly");
    }
}
