// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/MediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:28:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;





import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.MediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaFeed_ESTest extends MediaFeed_ESTest_scaffolding {
    
    

    
    
    
    @Test
    public void testGetPagination_ReturnsCorrectPagination() {
        // Arrange
        Pagination expectedPagination = new Pagination();
        // Optionally set fields on expectedPagination if any exist
        TagMediaFeed tagMediaFeed = new TagMediaFeed();

        // Use reflection or a setter if available to set the private field 'pagination'
        // Since no setter is provided, use reflection here:
        try {
            java.lang.reflect.Field paginationField = TagMediaFeed.class.getDeclaredField("pagination");
            paginationField.setAccessible(true);
            paginationField.set(tagMediaFeed, expectedPagination);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            fail("Failed to set pagination field via reflection: " + e.getMessage());
        }

        // Act
        Pagination actualPagination = tagMediaFeed.getPagination();

        // Assert
        assertSame(expectedPagination, actualPagination, "getPagination should return the exact Pagination instance set");
    }
}
