// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/model/OAuthConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:18:36 GMT 2024
 */
package org.jinstagram.auth.model;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.model.OAuthConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OAuthConfig_ESTest extends OAuthConfig_ESTest_scaffolding {
    
    @Test
    public void testGetCallback() {
        // Case 1: callback is provided
        OAuthConfig configWithCallback = new OAuthConfig("key", "secret", "http://callback.url", "scope", "display");
        assertEquals("http://callback.url", configWithCallback.getCallback());

        // Case 2: callback is null, should return OAuthConstants.OUT_OF_BAND
        OAuthConfig configWithNullCallback = new OAuthConfig("key", "secret", null, "scope", "display");
        assertEquals(OAuthConstants.OUT_OF_BAND, configWithNullCallback.getCallback());

        // Case 3: using constructor with only key and secret, callback should be OAuthConstants.OUT_OF_BAND
        OAuthConfig configMinimal = new OAuthConfig("key", "secret");
        assertEquals(OAuthConstants.OUT_OF_BAND, configMinimal.getCallback());
    }
}
