// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagInfoFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:14:28 GMT 2024
 */
package org.jinstagram.entity.tags;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagInfoFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagInfoFeed_ESTest extends TagInfoFeed_ESTest_scaffolding {
    
    
@Test
public void testToString() {
    TagInfoFeed tagInfoFeed = new TagInfoFeed();
    Meta meta = new Meta();
    TagInfoData tagInfoData = new TagInfoData();
    try {
        java.lang.reflect.Field metaField = TagInfoFeed.class.getDeclaredField("meta");
        metaField.setAccessible(true);
        metaField.set(tagInfoFeed, meta);
        java.lang.reflect.Field tagInfoField = TagInfoFeed.class.getDeclaredField("tagInfo");
        tagInfoField.setAccessible(true);
        tagInfoField.set(tagInfoFeed, tagInfoData);
    } catch (NoSuchFieldException e) {
        throw new RuntimeException(e);
    } catch (IllegalAccessException e) {
        throw new RuntimeException(e);
    }
    String expected = String.format("TagInfoFeed [meta=%s, tagInfo=%s]", meta, tagInfoData);
    assertEquals(expected, tagInfoFeed.toString());
}
}
