// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/http/URLUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:48:19 GMT 2024
 */
package org.jinstagram.http;
import java.net.URLDecoder;
import java.io.UnsupportedEncodingException;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.http.URLUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class URLUtils_ESTest extends URLUtils_ESTest_scaffolding {
    
    @Test
    public void testDecodeURIComponent() {
        // Test normal decoding
        String encoded = "Hello%20World%21";
        String expected = "Hello World!";
        assertEquals(expected, URLUtils.decodeURIComponent(encoded));

        // Test string with no encoding
        String plain = "JustAPlainString";
        assertEquals(plain, URLUtils.decodeURIComponent(plain));

        // Test empty string
        String empty = "";
        assertEquals(empty, URLUtils.decodeURIComponent(empty));

        // Test null input (should handle gracefully, but current method does not check null)
        // This test will throw NullPointerException if null is passed, so we skip it or handle it here
        // assertEquals(null, URLUtils.decodeURIComponent(null)); // would throw NPE

        // Test string with special characters
        String specialEncoded = "%40%23%24%25%5E%26*()";
        String specialExpected = "@#$%^&*()";
        assertEquals(specialExpected, URLUtils.decodeURIComponent(specialEncoded));

        // Test string with plus sign (space in URL encoding)
        String plusEncoded = "a+plus+sign";
        String plusExpected = "a plus sign";
        assertEquals(plusExpected, URLUtils.decodeURIComponent(plusEncoded));
    }
}
