// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/media/MediaInfoFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:05:00 GMT 2024
 */
package org.jinstagram.entity.media;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.media.MediaInfoFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.media.MediaInfoFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaInfoFeed_ESTest extends MediaInfoFeed_ESTest_scaffolding {


    
    @Test
    public void testSetMeta() {
        // Given
        Meta meta = new Meta();
        MediaInfoFeed mediaInfoFeed = new MediaInfoFeed();

        // When
        mediaInfoFeed.setMeta(meta);

        // Then
        assertEquals(meta, mediaInfoFeed.getMeta());
    }


    
    
    
    @Test
    public void testSetData() {
        MediaFeedData mockData = new MediaFeedData(); // Fixed line

        MediaInfoFeed mediaInfoFeed = new MediaInfoFeed();
        mediaInfoFeed.setData(mockData);
        assertEquals(mockData, mediaInfoFeed.getData());
    }


    
    @Test
    public void testSetMeta_1() {
        Meta testMeta = new Meta(); // Create a test Meta object
        MediaInfoFeed mediaInfoFeed = new MediaInfoFeed(); // Create a MediaInfoFeed object

        assertNull(mediaInfoFeed.getMeta()); // Initially meta should be null

        mediaInfoFeed.setMeta(testMeta); // Set the test Meta object
        assertEquals(testMeta, mediaInfoFeed.getMeta()); // Check if meta is set correctly
    }


    
    @Test
    public void testSetData_1() {
        // Given
        MediaInfoFeed mediaInfoFeed = new MediaInfoFeed();
        MediaFeedData testData = new MediaFeedData(); // You need to create an instance of MediaFeedData

        // When
        mediaInfoFeed.setData(testData);

        // Then
        assertEquals(testData, mediaInfoFeed.getData());
    }

}
