// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/TypeImpl_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:15:15 GMT 2024
 */
package com.zappos.json.util;



import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.util.TypeImpl;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TypeImpl_ESTest extends TypeImpl_ESTest_scaffolding {
    



@Test
public void testGetIterableImpl() {
    TypeImpl typeImplList = TypeImpl.getIterableImpl(List.class);
    assertEquals(List.class, typeImplList.getInfClass());
    assertEquals(ArrayList.class, typeImplList.getImplClass());
    
    TypeImpl typeImplCollection = TypeImpl.getIterableImpl(Collection.class);
    assertEquals(Collection.class, typeImplCollection.getInfClass());
    assertEquals(ArrayList.class, typeImplCollection.getImplClass());
    
    TypeImpl typeImplIterable = TypeImpl.getIterableImpl(Iterable.class);
    assertEquals(Iterable.class, typeImplIterable.getInfClass());
    assertEquals(ArrayList.class, typeImplIterable.getImplClass());
    
    try {
        TypeImpl typeImplAbstract = TypeImpl.getIterableImpl(AbstractList.class);
        fail("Expected RuntimeException was not thrown");
    } catch (RuntimeException e) {
        assertEquals("Cannot find appropriate implementation of collection type: AbstractList", e.getMessage());
    }
}
}
