// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
    




@Test
public void testMerge() {
    // Arrange
    RectangularTextContainer textContainer1 = new RectangularTextContainer(10.0f, 20.0f, 50.0f, 30.0f);
    RectangularTextContainer textContainer2 = new RectangularTextContainer(15.0f, 25.0f, 40.0f, 35.0f);

    // Add text elements to the text containers
    List<String> textElements1 = new ArrayList<>();
    textElements1.add("Text1");
    textElements1.add("Text2");
    textContainer1.getTextElements().addAll(textElements1);

    List<String> textElements2 = new ArrayList<>();
    textElements2.add("Text3");
    textElements2.add("Text4");
    textContainer2.getTextElements().addAll(textElements2);

    // Act
    RectangularTextContainer mergedContainer = textContainer1.merge(textContainer2);

    // Assert
    List<String> expectedMergedTextElements = new ArrayList<>();
    expectedMergedTextElements.addAll(textElements1);
    expectedMergedTextElements.addAll(textElements2);

    assertEquals("Merged text elements size is incorrect", expectedMergedTextElements.size(), mergedContainer.getTextElements().size());
    assertEquals("Merged text elements order is incorrect", expectedMergedTextElements, mergedContainer.getTextElements());
}
}
