// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagMediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:16:28 GMT 2024
 */
package org.jinstagram.entity.tags;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.tags.TagMediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagMediaFeed_ESTest extends TagMediaFeed_ESTest_scaffolding {
    @Test
    public void testGetData() {
        // Create a mock TagMediaFeed object
        TagMediaFeed tagMediaFeed = mock(TagMediaFeed.class);

        // Create a list of MediaFeedData to be returned by the mock object
        List<MediaFeedData> expectedData = new LinkedList<>();
        expectedData.add(new MediaFeedData());
        expectedData.add(new MediaFeedData());

        // Set up the mock object to return the expected data when getData() is called
        when(tagMediaFeed.getData()).thenReturn(expectedData);

        // Call the method under test
        List<MediaFeedData> actualData = tagMediaFeed.getData();

        // Verify that the returned data matches the expected data
        assertEquals(expectedData, actualData);
    }
}
