// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {


@Test
public void testToString() {
    float top = 10f;
    float left = 20f;
    float width = 30f;
    float height = 40f;
    Rectangle rect = new Rectangle(top, left, width, height);
    String str = rect.toString();
    float expectedBottom = top + height;
    float expectedRight = left + width;
    String expectedSuffix = String.format(",bottom=%f,right=%f]", expectedBottom, expectedRight);
    assertTrue("toString should end with bottom and right coordinates",
            str.endsWith(expectedSuffix));
    int lastBracketIndex = str.lastIndexOf(']');
    assertTrue("toString should contain '[' before the suffix", lastBracketIndex > 0);
    String prefix = str.substring(0, lastBracketIndex);
    assertTrue("toString prefix should start with superclass toString without last character",
            prefix.equals(rect.getClass().getSuperclass().cast(rect).toString().substring(0, rect.getClass().getSuperclass().cast(rect).toString().length() - 1)));
}
}
