// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;





import java.util.Arrays;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {



    
    
    
    
    @Test
    public void testSetTextElements_ReplacesTextElements() {
        TestRectangularTextContainer<String> container = new TestRectangularTextContainer<>(0, 0, 100, 100);

        // Initial list of text elements
        List<String> initialElements = Arrays.asList("one", "two");
        container.setTextElements(initialElements);
        assertEquals(initialElements, container.textElements, "Initial text elements should be set correctly");

        // New list of text elements to replace the old one
        List<String> newElements = Arrays.asList("three", "four", "five");
        container.setTextElements(newElements);
        assertEquals(newElements, container.textElements, "Text elements should be replaced with new list");

        // Test with empty list
        List<String> emptyElements = Arrays.asList();
        container.setTextElements(emptyElements);
        assertEquals(emptyElements, container.textElements, "Text elements should be replaced with empty list");

        // Test with null list (if allowed, otherwise this test can be removed)
        container.setTextElements(null);
        assertEquals(null, container.textElements, "Text elements should be set to null if null is passed");
    }
}
