// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;





import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {





    
    @Test
    void testMerge_whenThisIsBeforeOther_shouldAppendOtherTextElements() {
        TestRectangularTextContainer container1 = new TestRectangularTextContainer(1, 1, 2, 2);
        container1.getTextElements().add("A");
        container1.getTextElements().add("B");

        TestRectangularTextContainer container2 = new TestRectangularTextContainer(2, 2, 3, 3);
        container2.getTextElements().add("C");
        container2.getTextElements().add("D");

        TestRectangularTextContainer merged = container1.merge(container2);

        // Since container1.top < container2.top, container2's text elements should be appended
        List<String> expectedText = List.of("A", "B", "C", "D");
        assertEquals(expectedText, merged.getTextElements());

        // Spatial properties should be merged correctly
        assertEquals(1, merged.getTop());
        assertEquals(1, merged.getLeft());
        assertEquals(4, merged.getWidth());  // from left=1 to right=5 (2+3)
        assertEquals(4, merged.getHeight()); // from top=1 to bottom=5 (2+3)
    }
}
