// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Table_ESTest extends Table_ESTest_scaffolding {
@Test
public void testEmpty() {
    Table emptyTable = Table.empty();
    // The extraction method should be an empty string
    assertEquals("", emptyTable.getExtractionMethod());
    // The row count should be zero for an empty table
    assertEquals(0, emptyTable.getRowCount());
    // The column count should be zero for an empty table
    assertEquals(0, emptyTable.getColCount());
    // The page number should be zero by default (assuming default is 0)
    assertEquals(0, emptyTable.getPageNumber());
    // The rows list should be empty
    assertTrue(emptyTable.getRows().isEmpty());
}
}
