// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
@Test
public void testIsSameChar() {
    // Create TextElements with text "aaa"
    TextElement te1 = new TextElement(0, 0, 1, 1, "a");
    TextElement te2 = new TextElement(0, 1, 1, 1, "a");
    TextElement te3 = new TextElement(0, 2, 1, 1, "a");
    List<TextElement> elements = new ArrayList<>();
    elements.add(te1);
    elements.add(te2);
    elements.add(te3);

    TextChunk chunk = new TextChunk(elements);

    // Test with array containing only 'a'
    Character[] chars1 = new Character[] {'a'};
    assertTrue(chunk.isSameChar(chars1));

    // Test with array containing 'a' and 'b'
    Character[] chars2 = new Character[] {'a', 'b'};
    assertTrue(chunk.isSameChar(chars2));

    // Test with array containing 'b' only
    Character[] chars3 = new Character[] {'b'};
    assertFalse(chunk.isSameChar(chars3));

    // Test with array containing 'a' and 'c'
    Character[] chars4 = new Character[] {'a', 'c'};
    assertTrue(chunk.isSameChar(chars4));

    // Test with empty array
    Character[] chars5 = new Character[] {};
    assertFalse(chunk.isSameChar(chars5));

    // Test with chunk containing mixed characters "aba"
    TextElement te4 = new TextElement(0, 3, 1, 1, "b");
    List<TextElement> mixedElements = new ArrayList<>();
    mixedElements.add(te1);
    mixedElements.add(te4);
    mixedElements.add(te3);
    TextChunk mixedChunk = new TextChunk(mixedElements);

    // Should be true for 'a' and 'b'
    assertTrue(mixedChunk.isSameChar(chars2));

    // Should be false for 'a' only
    assertFalse(mixedChunk.isSameChar(chars1));
}
}
