// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/CarouselMedia_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:26:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;


import org.jinstagram.entity.common.GridPosition;
import org.jinstagram.entity.common.User;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import org.jinstagram.entity.common.CarouselMedia;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import org.mockito.Mockito;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CarouselMedia_ESTest extends CarouselMedia_ESTest_scaffolding {
    


    


@Test
public void testSetUsersInPhotoList() {
    // Arrange
    UsersInPhoto user1 = new UsersInPhoto();
    UsersInPhoto user2 = new UsersInPhoto();
    List<UsersInPhoto> usersList = new ArrayList<>();
    
    user1.setUser(new User("user1"));
    user1.setPosition(new GridPosition(1, 2));
    
    user2.setUser(new User("user2"));
    user2.setPosition(new GridPosition(3, 4));
    
    usersList.add(user1);
    usersList.add(user2);
    
    CarouselMedia carouselMedia = new CarouselMedia();
    
    // Act
    carouselMedia.setUsersInPhotoList(usersList);
    
    // Assert
    assertEquals(2, carouselMedia.getUsersInPhotoList().size());
    assertEquals("user1", carouselMedia.getUsersInPhotoList().get(0).getUser().getUsername());
    assertEquals(1, carouselMedia.getUsersInPhotoList().get(0).getPosition().getX());
    assertEquals(2, carouselMedia.getUsersInPhotoList().get(0).getPosition().getY());
    
    assertEquals("user2", carouselMedia.getUsersInPhotoList().get(1).getUser().getUsername());
    assertEquals(3, carouselMedia.getUsersInPhotoList().get(1).getPosition().getX());
    assertEquals(4, carouselMedia.getUsersInPhotoList().get(1).getPosition().getY());
}
}
