// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/PaginationHelper_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:15:36 GMT 2024
 */
package org.jinstagram.utils;



import org.jinstagram.entity.common.Page;
import org.jinstagram.entity.common.PaginationHelper;
import org.jinstagram.exceptions.OAuthException;
import org.apache.commons.lang3.exception.ExceptionUtils; // Adding an import for ExceptionUtils to handle exceptions more effectively
import static org.mockito.Mockito.*;
import org.apache.commons.lang3.StringUtils;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.utils.PaginationHelper;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.utils.PaginationHelper;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class PaginationHelper_ESTest extends PaginationHelper_ESTest_scaffolding {
    






@Test
public class PaginationHelperTest {

    // Arrange:
    Pagination pagination = new Pagination();
    String apiUrl = "https://example.com/api/";

    // Act:
    @Test
    public void testParseNextUrl() {
        pagination.setNextUrl("https://example.com/api/method?param1=value1&param2=value2");

        // Act and Assert:
        try {
            Page result = PaginationHelper.parseNextUrl(pagination, apiUrl);
            assertNotNull(result);
            assertEquals("method", result.getMethodName());
            assertEquals("value1", result.getParams().get("param1"));
            assertEquals("value2", result.getParams().get("param2"));
        } catch (OAuthException e) {
            fail("Unexpected exception thrown");
        }
    }

    @Test
    public void testParseNextUrlWithBlankNextUrl() {
        pagination.setNextUrl("");

        // Act and Assert:
        try {
            PaginationHelper.parseNextUrl(pagination, apiUrl);
            fail("Expected OAuthException not thrown");
        } catch (OAuthException e) {
            // Expected behavior
        }
    }
}
}
