// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/JavaDateFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:35:46 GMT 2024
 */
package com.zappos.json.format;








import java.text.SimpleDateFormat;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.text.ParseException;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JavaDateFormatter_ESTest extends JavaDateFormatter_ESTest_scaffolding {

    
    
    

    
    

    @Test
    public void testParse_withPatternAndWithoutPattern() throws Exception {
        JavaDateFormatter formatterWithPattern = new JavaDateFormatter() {
            private final String pattern = "yyyy-MM-dd";
            public String getPattern() {
                return pattern;
            }
        };
        JavaDateFormatter formatterWithoutPattern = new JavaDateFormatter() {
            public String getPattern() {
                return null;
            }
        };
        ZapposJson dummyZapposJson = null; 
        String dateString = "2023-04-20";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date expectedDate = sdf.parse(dateString);
        long timestamp = 1681948800000L; 
        String timestampString = Long.toString(timestamp);
        Date expectedDateFromTimestamp = new Date(timestamp);
        Date actualDateFromPattern = formatterWithPattern.parse(dummyZapposJson, dateString);
        Date actualDateFromTimestamp = formatterWithoutPattern.parse(dummyZapposJson, timestampString);

        assertEquals(expectedDate, actualDateFromPattern);
        assertEquals(expectedDateFromTimestamp, actualDateFromTimestamp);
    }
}
