// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonBeanAttribute_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:48:09 GMT 2024
 */
package com.zappos.json;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.annot.JsonEnum;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonBeanAttribute_ESTest extends JsonBeanAttribute_ESTest_scaffolding {

    
    
    
    
    @Test
    public void testSetEnumValue_assignsEnumValueAndReturnsThis() {
        // Arrange:
        JsonBeanAttribute jsonBeanAttribute = new JsonBeanAttribute();
        EnumValue enumValue = new EnumValue("TEST_VALUE");

        // Act:
        JsonBeanAttribute returnedInstance = jsonBeanAttribute.setEnumValue(enumValue);

        // Assert:
        // Check that the returned instance is the same as the original instance (method chaining)
        assertSame(jsonBeanAttribute, returnedInstance, "setEnumValue should return the same instance for chaining");

        // Since enumValue field is private, we cannot access it directly.
        // Use reflection to verify the field was set correctly.
        try {
            java.lang.reflect.Field field = JsonBeanAttribute.class.getDeclaredField("enumValue");
            field.setAccessible(true);
            Object fieldValue = field.get(jsonBeanAttribute);
            assertEquals(enumValue, fieldValue, "enumValue field should be assigned the provided EnumValue instance");
        } catch (NoSuchFieldException | IllegalAccessException e) {
            fail("Reflection failed to access enumValue field: " + e.getMessage());
        }
    }
}
