// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.*;
import technology.tabula.Ruling;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    
    
    @Test
    public void testCollapseOrientedRulings() {
        List<Ruling> emptyList = new ArrayList<>();
        List<Ruling> result1 = Ruling.collapseOrientedRulings(emptyList, 5);
        assertTrue(result1.isEmpty());
        
        Ruling singleLine = new Ruling(0, 0, 10, 10);
        List<Ruling> singleList = new ArrayList<>();
        singleList.add(singleLine);
        List<Ruling> result2 = Ruling.collapseOrientedRulings(singleList, 5);
        assertEquals(1, result2.size());
        assertEquals(singleLine, result2.get(0));
        
        Ruling line1 = new Ruling(0, 0, 10, 10);
        Ruling line2 = new Ruling(5, 5, 10, 10);
        List<Ruling> overlappingList = new ArrayList<>();
        overlappingList.add(line1);
        overlappingList.add(line2);
        
        List<Ruling> result3 = Ruling.collapseOrientedRulings(overlappingList, 5);
        assertEquals(1, result3.size());
        Ruling expectedMergedLine = new Ruling(0, 0, 10, 10);
        assertEquals(expectedMergedLine, result3.get(0));
    }
}
