// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.lang.reflect.Field;
import java.util.Map;
import java.util.List;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {
    @Test
    public void testGetSecondGenericType() throws NoSuchFieldException {
        // Field with two generic parameters: Map<String, Integer>
        Field mapField = TestClassWithTwoGenerics.class.getDeclaredField("mapField");
        Class<?> secondGenericType = Reflections.getSecondGenericType(mapField);
        assertNotNull("Second generic type should not be null for Map<String, Integer>", secondGenericType);
        assertEquals("Second generic type should be Integer.class", Integer.class, secondGenericType);

        // Field with one generic parameter: List<String>
        Field listField = TestClassWithOneGeneric.class.getDeclaredField("listField");
        Class<?> secondGenericTypeList = Reflections.getSecondGenericType(listField);
        assertNull("Second generic type should be null for List<String>", secondGenericTypeList);

        // Field with no generic parameters: String
        Field plainField = TestClassWithNoGeneric.class.getDeclaredField("plainField");
        Class<?> secondGenericTypePlain = Reflections.getSecondGenericType(plainField);
        assertNull("Second generic type should be null for non-generic field", secondGenericTypePlain);
    }
}
