// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {
@Test
public void testGetValueFormatter() {
    ZapposJson zapposJson = ZapposJson.getInstance();

    // Test known registered formatter for Date.class
    ValueFormatter<Object> dateFormatter = zapposJson.getValueFormatter(Date.class);
    org.junit.Assert.assertNotNull("Formatter for Date.class should not be null", dateFormatter);

    // Test known registered formatter for java.sql.Date.class
    ValueFormatter<Object> sqlDateFormatter = zapposJson.getValueFormatter(java.sql.Date.class);
    org.junit.Assert.assertNotNull("Formatter for java.sql.Date.class should not be null", sqlDateFormatter);

    // Test known registered formatter for java.math.BigInteger.class
    ValueFormatter<Object> bigIntegerFormatter = zapposJson.getValueFormatter(java.math.BigInteger.class);
    org.junit.Assert.assertNotNull("Formatter for BigInteger.class should not be null", bigIntegerFormatter);

    // Test unknown class returns null
    class DummyClass {}
    ValueFormatter<Object> dummyFormatter = zapposJson.getValueFormatter(DummyClass.class);
    org.junit.Assert.assertNull("Formatter for unregistered class should be null", dummyFormatter);
}
}
