// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    
    





@Test
public void testAddMethod() {
    // Arrange
    TextElement textElement1 = new TextElement(10, 20, 30, 40);
    TextElement textElement2 = new TextElement(50, 60, 70, 80);
    List<TextElement> textElements = new ArrayList<>();
    textElements.add(textElement1);
    textElements.add(textElement2);
    TextChunk textChunk = new TextChunk(textElement1);

    // Act
    textChunk.add(textElements);

    // Assert
    assertEquals(2, textChunk.getElements().size()); // Expected size should be 2 after adding elements
    assertEquals(textElement1, textChunk.getElements().get(0)); // First element should match textElement1
    assertEquals(textElement2, textChunk.getElements().get(1)); // Second element should match textElement2
}
}
