// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testAddTextChunk() {
        // Create a Line object
        Line line = new Line();
        
        // Create TextChunk objects
        TextChunk textChunk1 = new TextChunk("TextChunk1");
        TextChunk textChunk2 = new TextChunk("TextChunk2");
        
        // Add textChunk1 at index 0
        line.addTextChunk(0, textChunk1);
        
        // Verify that textChunk1 is added at index 0
        assertEquals(textChunk1, line.getTextElements().get(0));
        
        // Add textChunk2 at index 1
        line.addTextChunk(1, textChunk2);
        
        // Verify that textChunk2 is added at index 1
        assertEquals(textChunk2, line.getTextElements().get(1));
        
        // Add textChunk2 at index 2
        TextChunk textChunk3 = new TextChunk("TextChunk3");
        line.addTextChunk(2, textChunk3);
        
        // Verify that textChunk3 is added at index 2
        assertEquals(textChunk3, line.getTextElements().get(2));
    }
}
