// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/InstagramAuthService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:15:21 GMT 2024
 */
package org.jinstagram.auth;





import static org.mockito.Mockito.*;
import org.jinstagram.auth.Proxy;
import org.jinstagram.service.InstagramService;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.OAuthConfig;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.mockito.Mockito;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetAddress;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jinstagram.auth.InstagramAuthService;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramAuthService_ESTest extends InstagramAuthService_ESTest_scaffolding {
    
    
    
    




@Test
public void testBuild_WithValidParameters_ReturnsInstagramService() {
    // Arrange
    String apiKey = "testApiKey";
    String apiSecret = "testApiSecret";
    String callback = "testCallback";
    String scope = "testScope";
    String display = "testDisplay";
    Proxy requestProxy = Mockito.mock(Proxy.class);
    
    InstagramAuthService authService = new InstagramAuthService();
    authService.apiKey(apiKey);
    authService.apiSecret(apiSecret);
    authService.callback(callback);
    authService.scope(scope);
    authService.display(display);
    authService.proxy(requestProxy);

    InstagramApi mockApi = Mockito.mock(InstagramApi.class);
    Mockito.when(mockApi.createService(Mockito.any(OAuthConfig.class))).thenReturn(Mockito.mock(InstagramService.class));

    // Act
    InstagramService result = authService.build();

    // Assert
    assertNotNull(result);
    Mockito.verify(mockApi).createService(Mockito.any(OAuthConfig.class));
    assertEquals(apiKey, authService.getApiKey());
    assertEquals(apiSecret, authService.getApiSecret());
    assertEquals(callback, authService.getCallback());
    assertEquals(scope, authService.getScope());
    assertEquals(display, authService.getDisplay());
    assertEquals(requestProxy, authService.getRequestProxy());
}
}
