// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;




import java.util.ArrayList;
import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {

    
    

    
    @Test
    public void testSetTextElements_replacesTextChunksWithNewList() {
        // Arrange:
        Line line = new Line();

        List<TextChunk> initialChunks = new ArrayList<>();
        initialChunks.add(new TextChunk("initial1"));
        initialChunks.add(new TextChunk("initial2"));
        line.setTextElements(initialChunks);

        List<TextChunk> newChunks = new ArrayList<>();
        newChunks.add(new TextChunk("new1"));
        newChunks.add(new TextChunk("new2"));
        newChunks.add(new TextChunk("new3"));

        // Act:
        line.setTextElements(newChunks);

        // Assert:
        assertEquals(newChunks, line.textChunks, "The textChunks list should be replaced with the new list");
    }
}
