// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;





import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    


    
    

    @Test
    void testGetAttributeInfosReturnsInternalList() {
        TypeInfo typeInfo = new TypeInfo(String.class);

        // Initially, the list should be empty
        List<AttributeInfo> attrs = typeInfo.getAttributeInfos();
        assertNotNull(attrs, "getAttributeInfos() should not return null");
        assertTrue(attrs.isEmpty(), "Initial attribute list should be empty");

        // Add an AttributeInfo instance to the internal list
        AttributeInfo attr1 = new AttributeInfo();
        attrs.add(attr1);

        // The list returned by getAttributeInfos() should reflect the added element
        List<AttributeInfo> attrsAfterAdd = typeInfo.getAttributeInfos();
        assertEquals(1, attrsAfterAdd.size(), "Attribute list size should be 1 after adding an element");
        assertSame(attr1, attrsAfterAdd.get(0), "The added AttributeInfo should be present in the list");

        // Modifying the returned list should affect the internal list (confirming it's the same list)
        attrsAfterAdd.clear();
        assertTrue(typeInfo.getAttributeInfos().isEmpty(), "Clearing the returned list should clear the internal list");
    }
}
