// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonBeanAttribute_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:48:09 GMT 2024
 */
package com.zappos.json;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.EnumValue;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.annot.JsonEnum;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonBeanAttribute_ESTest extends JsonBeanAttribute_ESTest_scaffolding {
    


    
    
    @Test
    public void testSetEnumValue_ShouldAssignEnumValueAndReturnThis() {
        JsonBeanAttribute jsonBeanAttribute = new JsonBeanAttribute();
        EnumValue enumValue = new EnumValue();

        JsonBeanAttribute returned = jsonBeanAttribute.setEnumValue(enumValue);

        // Verify that the enumValue field is set correctly
        assertSame(enumValue, returned.enumValue, "The enumValue field should be set to the provided EnumValue instance");
        // Verify that the returned object is the same instance (for method chaining)
        assertSame(jsonBeanAttribute, returned, "The method should return the same JsonBeanAttribute instance for chaining");
    }
}
