// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;
import java.awt.geom.Rectangle2D;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import static org.junit.Assert.*;
import technology.tabula.Ruling;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    
@Test
public void testCollapseOrientedRulings() {
    // Arrange:
    List<Ruling> lines = new LinkedList<>();
    Ruling ruling1 = new Ruling(0, 0, 10, 10);
    Ruling ruling2 = new Ruling(5, 5, 15, 15);
    Ruling ruling3 = new Ruling(20, 20, 10, 10);
    lines.add(ruling1);
    lines.add(ruling2);
    lines.add(ruling3);

    // Act:
    List<Ruling> collapsedRulings = Ruling.collapseOrientedRulings(lines);
    
    // Assert:
    assertEquals(2, collapsedRulings.size());
}
}
