// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Reflections_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:11:21 GMT 2024
 */
package com.zappos.json.util;



import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.lang.reflect.Field;
import java.lang.reflect.Type;
import java.lang.reflect.ParameterizedType;
import java.util.List;
import java.util.ArrayList;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import java.lang.reflect.Type;
import java.lang.reflect.ParameterizedType;
import java.util.List;
import java.util.ArrayList;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Reflections;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Reflections_ESTest extends Reflections_ESTest_scaffolding {


    

    
    @Test
    public void testGetGenericTypes_variousFields() throws NoSuchFieldException {
        class TestClass {
            List<String> stringList;
            @SuppressWarnings("rawtypes")
            List rawList;
            List<Integer> integerList;
            String simpleField;
        }
        Field stringListField = TestClass.class.getDeclaredField("stringList");
        Field rawListField = TestClass.class.getDeclaredField("rawList");
        Field integerListField = TestClass.class.getDeclaredField("integerList");
        Field simpleField = TestClass.class.getDeclaredField("simpleField");
        Class<?>[] stringListTypes = Reflections.getGenericTypes(stringListField);
        Class<?>[] rawListTypes = Reflections.getGenericTypes(rawListField);
        Class<?>[] integerListTypes = Reflections.getGenericTypes(integerListField);
        Class<?>[] simpleFieldTypes = Reflections.getGenericTypes(simpleField);
        assertNotNull("Expected generic types for stringList", stringListTypes);
        assertEquals(1, stringListTypes.length);
        assertEquals(String.class, stringListTypes[0]);

        assertNull("Expected null for rawList (no generic type info)", rawListTypes);

        assertNotNull("Expected generic types for integerList", integerListTypes);
        assertEquals(1, integerListTypes.length);
        assertEquals(Integer.class, integerListTypes[0]);
        assertNull("Expected null for simpleField (not parameterized)", simpleFieldTypes);
    }


    

@Test
        public void annotatedMethod() {
        }


    
    @Test
    public void testGetGenericParameterTypes() throws NoSuchMethodException {
        // Arrange:
        // Define a class with methods having generic parameters to test Reflections.getGenericParameterTypes
        class TestClass {
            public void methodWithTwoGenerics(java.util.Map<String, Integer> param) {}
            public void methodWithoutGenerics(String param) {}
        }
        Method methodWithGenerics = TestClass.class.getMethod("methodWithTwoGenerics", java.util.Map.class);
        Method methodWithoutGenerics = TestClass.class.getMethod("methodWithoutGenerics", String.class);

        // Act:
        Class<?>[] resultWithGenerics = Reflections.getGenericParameterTypes(methodWithGenerics);
        Class<?>[] resultWithoutGenerics = Reflections.getGenericParameterTypes(methodWithoutGenerics);

        // Assert:
        assertNotNull("Result should not be null for method with generics", resultWithGenerics);
        assertEquals("There should be 2 generic parameter types", 2, resultWithGenerics.length);
        assertEquals("First generic parameter should be String.class", String.class, resultWithGenerics[0]);
        assertEquals("Second generic parameter should be Integer.class", Integer.class, resultWithGenerics[1]);
        assertNull("Result should be null for method without generics", resultWithoutGenerics);
    }


    
    
@Test
        public void dummyMethod() {
        }


    
@Test
public void testGetSecondGenericParameterType() throws NoSuchMethodException {
    // Arrange:
    class Sample {
        public <T, U> void methodWithTwoGenerics(T t, U u) {}
        public <T> void methodWithOneGeneric(T t) {}
        public void methodWithNoParams() {}
    }
    Method methodWithTwoGenerics = Sample.class.getMethod("methodWithTwoGenerics", Object.class, Object.class);
    Method methodWithOneGeneric = Sample.class.getMethod("methodWithOneGeneric", Object.class);
    Method methodWithNoParams = Sample.class.getMethod("methodWithNoParams");

    // Act & Assert:

    // Since getGenericParameterTypes is undefined and cannot be controlled,
    // the focal method returns null if the returned array is null or length <= 1.

    // Case: method with no parameters -> should return null
    assertNull(Reflections.getSecondGenericParameterType(methodWithNoParams));

    // Case: method with one parameter -> should return null
    assertNull(Reflections.getSecondGenericParameterType(methodWithOneGeneric));

    // Case: method with two parameters -> without getGenericParameterTypes implementation,
    // the method likely returns null (since types would be null or not as expected).
    // So the safe assumption is the method returns null.
    assertNull(Reflections.getSecondGenericParameterType(methodWithTwoGenerics));
}


    
@Test
public void testClassPresent() {
    // Arrange:
    String existingClass = "java.lang.String";
    String nonExistingClass = "non.existing.ClassName12345";

    // Act:
    boolean presentResult = Reflections.classPresent(existingClass);
    boolean absentResult = Reflections.classPresent(nonExistingClass);

    // Assert:
    assertTrue("Expected classPresent to return true for existing class", presentResult);
    assertFalse("Expected classPresent to return false for non-existing class", absentResult);
}

}
