// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;



import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.util.Strings;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Strings_ESTest extends Strings_ESTest_scaffolding {


    

    
    @Test
    public void testRandomNumberZeroLength() {
        int length = 0;
        String result = Strings.randomNumber(length);
        assertNotNull("Result should not be null even if length is zero", result);
        assertEquals("Result length should be zero when requested length is zero", 0, result.length());
    }


    
    
    @Test
    public void testIsNumber() {
        assertFalse(Strings.isNumber(null));
        assertFalse(Strings.isNumber(""));
        assertFalse(Strings.isNumber("a123"));
        assertFalse(Strings.isNumber("+123"));
        assertTrue(Strings.isNumber("0"));
        assertTrue(Strings.isNumber("123"));
        assertTrue(Strings.isNumber("-123"));
        assertTrue(Strings.isNumber("0.5"));
        assertTrue(Strings.isNumber("-0.5"));
        assertTrue(Strings.isNumber("123.456"));
        assertFalse(Strings.isNumber("123.4.56"));
        assertFalse(Strings.isNumber("-123.4.56"));
        assertFalse(Strings.isNumber("12a34"));
        assertFalse(Strings.isNumber("123-456"));
        assertTrue(Strings.isNumber("123."));     // new assertion for trailing decimal point
        assertTrue(Strings.isNumber("-123."));    // additional check for trailing decimal with minus
    }


    
    @Test
    public void testRandom() {
        char[] chars = {'a', 'b', 'c', 'd', 'e'};
        String randomString = Strings.random(5, chars);
        assertEquals(5, randomString.length());

        for (int i = 0; i < randomString.length(); i++) {
            char c = randomString.charAt(i);
            boolean found = false;
            for (char ch : chars) {
                if (ch == c) {
                    found = true;
                    break;
                }
            }
            assertTrue(found);
        }
    }


    

    
    @Test
    public void testRandomAlphabetic() {
        int length = 100;
        String result = Strings.randomAlphabetic(length);
        assertNotNull("Result should not be null", result);
        assertEquals("Length should match", length, result.length());
        for (int i = 0; i < length; i++) {
            char ch = result.charAt(i);
            boolean isUppercase = (ch >= 'A' && ch <= 'Z');
            boolean isLowercase = (ch >= 'a' && ch <= 'z');

            assertTrue("Character at index " + i + " should be an alphabetic letter", isUppercase || isLowercase);
        }
    }



    @Test
    public void testFormat() {
        String pattern = "Hello @, you have @ new messages.";
        Object[] args = {"Alice", 5};
        String result = Strings.format(pattern, args[0], args[1]);
             
}

}
