// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/TypeImpl_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:15:15 GMT 2024
 */
package com.zappos.json.util;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import com.zappos.json.util.TypeImpl;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.Map;
import java.util.HashMap;
import java.util.AbstractMap;
import java.util.SortedMap;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.*;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import java.util.Map;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TypeImpl_ESTest extends TypeImpl_ESTest_scaffolding {


    
    
    
    @Test
    public void testGetMapImpl() {
        TypeImpl mapImpl = TypeImpl.getMapImpl(Map.class);
        assertEquals(HashMap.class, mapImpl.getImplClass());

        TypeImpl abstractMapImpl = TypeImpl.getMapImpl(AbstractMap.class);
        assertEquals(HashMap.class, abstractMapImpl.getImplClass());

        TypeImpl concurrentMapImpl = TypeImpl.getMapImpl(ConcurrentMap.class);
        assertEquals(ConcurrentHashMap.class, concurrentMapImpl.getImplClass());

        TypeImpl sortedMapImpl = TypeImpl.getMapImpl(SortedMap.class);
        assertEquals(TreeMap.class, sortedMapImpl.getImplClass());

        TypeImpl concreteMapImpl = TypeImpl.getMapImpl(HashMap.class);
        assertEquals(HashMap.class, concreteMapImpl.getImplClass());

        try {
            TypeImpl invalidMapImpl = TypeImpl.getMapImpl(Map.Entry.class);
            fail("Expected RuntimeException not thrown");
        } catch (RuntimeException e) {
            assertTrue(e.getMessage().contains("Cannot find appropriate implementation"));
        }
    }


    
    
    @Test
    public void testGetIterableImpl() {
        TypeImpl typeImplList = TypeImpl.getIterableImpl(List.class);
        assertEquals(List.class, typeImplList.getInfClass());
        assertEquals(ArrayList.class, typeImplList.getImplClass());

        TypeImpl typeImplCollection = TypeImpl.getIterableImpl(Collection.class);
        assertEquals(Collection.class, typeImplCollection.getInfClass());
        assertEquals(ArrayList.class, typeImplCollection.getImplClass());

        try {
            TypeImpl typeImplAbstract = TypeImpl.getIterableImpl(AbstractList.class);
            fail("Expected RuntimeException was not thrown");
        } catch (RuntimeException e) {
            assertEquals("Cannot find appropriate implementation of collection type: java.util.AbstractList", e.getMessage());
        }
    }


    
    @Test
    public void testGetInfClass() {
        // Use the static factory method to get a TypeImpl instance for Map interface
        TypeImpl typeImpl = TypeImpl.getMapImpl(Map.class);

        Class<?> retrievedInfClass = typeImpl.getInfClass();
        assertEquals(Map.class, retrievedInfClass);
    }

}
