// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/JsonReaderCodeGenerator_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:55:24 GMT 2024
 */
package com.zappos.json;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonBeanAttribute;
import com.zappos.json.JsonBeanIntrospector;
import com.zappos.json.JsonReaderCodeGenerator;
import com.zappos.json.JsonReaderInvoker;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimeInstantFormatter;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JsonReaderCodeGenerator_ESTest extends JsonReaderCodeGenerator_ESTest_scaffolding {
    



    
    
    @Test
    void testAddAttributeInfo() {
        TypeInfo typeInfo = new TypeInfo(String.class);

        JsonBeanAttribute detail1 = new JsonBeanAttribute("attr1", "value1");
        AttributeInfo attrInfo1 = typeInfo.addAttributeInfo(Integer.class, detail1);

        // Verify returned AttributeInfo is not null
        assertNotNull(attrInfo1);

        // Verify the returned AttributeInfo has correct type and detail
        assertEquals(Integer.class, attrInfo1.getType());
        assertEquals(detail1, attrInfo1.getDetail());

        // Verify the internal list contains the newly added AttributeInfo
        List<AttributeInfo> attrInfos = typeInfo.getAttrInfos();
        assertEquals(1, attrInfos.size());
        assertTrue(attrInfos.contains(attrInfo1));

        // Add another attribute info to verify multiple additions
        JsonBeanAttribute detail2 = new JsonBeanAttribute("attr2", "value2");
        AttributeInfo attrInfo2 = typeInfo.addAttributeInfo(Double.class, detail2);

        assertNotNull(attrInfo2);
        assertEquals(Double.class, attrInfo2.getType());
        assertEquals(detail2, attrInfo2.getDetail());

        attrInfos = typeInfo.getAttrInfos();
        assertEquals(2, attrInfos.size());
        assertTrue(attrInfos.contains(attrInfo2));
    }
}
