// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Strings_ESTest extends Strings_ESTest_scaffolding {
    


    
    

    
    @Test
    public void testRandom() {
        char[] chars = {'a', 'b', 'c', 'd', 'e'};
        int length = 10;

        String result = Strings.random(length, chars);

        // Check length
        assertEquals(length, result.length(), "Resulting string length should be " + length);

        // Check characters are from the input array
        for (char ch : result.toCharArray()) {
            boolean found = false;
            for (char c : chars) {
                if (ch == c) {
                    found = true;
                    break;
                }
            }
            assertTrue(found, "Character '" + ch + "' should be in the input chars array");
        }

        // Test with empty chars array - should throw IllegalArgumentException or similar
        char[] emptyChars = {};
        assertThrows(IllegalArgumentException.class, () -> Strings.random(5, emptyChars));

        // Test with zero length - should return empty string
        String emptyResult = Strings.random(0, chars);
        assertEquals("", emptyResult, "Result should be empty string when length is zero");

        // Test with length 1
        String singleCharResult = Strings.random(1, chars);
        assertEquals(1, singleCharResult.length());
        assertTrue(new String(chars).indexOf(singleCharResult.charAt(0)) >= 0);

        // Test with null chars array - should throw NullPointerException
        assertThrows(NullPointerException.class, () -> Strings.random(5, null));
    }
}
