// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/Strings_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:13:31 GMT 2024
 */
package com.zappos.json.util;




import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.Strings;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Strings_ESTest extends Strings_ESTest_scaffolding {
    
    



@Test
public void testRandomAlphabetic() {
    int length = 10;
    String result = Strings.randomAlphabetic(length);
    Assert.assertNotNull(result, "Result should not be null");

    Assert.assertEquals(result.length(), length, "Result length should match input length");

    for (char c : result.toCharArray()) {
        Assert.assertTrue((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'),
                "Character should be alphabetic: " + c);
    }
    String emptyResult = Strings.randomAlphabetic(0);
    Assert.assertNotNull(emptyResult, "Result should not be null for zero length");
    Assert.assertEquals(emptyResult.length(), 0, "Result length should be zero for zero input");
    try {
        Strings.randomAlphabetic(-1);
        Assert.fail("Expected NegativeArraySizeException to be thrown");
    } catch (NegativeArraySizeException e) {
    }
}
}
