// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/InstagramAuthService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:15:21 GMT 2024
 */
package org.jinstagram.auth;





import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetAddress;
import java.net.Proxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jinstagram.auth.InstagramAuthService;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramAuthService_ESTest extends InstagramAuthService_ESTest_scaffolding {



    
    
    @Test
    public void testProxyMethod_SetsRequestProxyAndReturnsSameInstance() {
        InstagramAuthService service = new InstagramAuthService();
        Proxy proxy = Proxy.NO_PROXY;

        InstagramAuthService returnedService = service.proxy(proxy);

        // Verify that the returned instance is the same as the original instance
        assertSame(service, returnedService, "proxy() should return the same InstagramAuthService instance");

        // Use reflection to verify that the private field requestProxy is set correctly
        try {
            java.lang.reflect.Field field = InstagramAuthService.class.getDeclaredField("requestProxy");
            field.setAccessible(true);
            Object actualProxy = field.get(service);
            assertSame(proxy, actualProxy, "requestProxy field should be set to the provided Proxy instance");
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to access requestProxy field via reflection", e);
        }
    }
}
