// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/oembed/OembedInformation_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:07:06 GMT 2024
 */
package org.jinstagram.entity.oembed;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OembedInformation_ESTest extends OembedInformation_ESTest_scaffolding {
@Test
public void testSetMediaId() {
    OembedInformation info = new OembedInformation();
    String testMediaId = "12345";
    info.setMediaId(testMediaId);
    // Since there is no getMediaId() method defined in the focal context, 
    // we rely on toString() or other accessible methods to verify the change.
    // Assuming toString() includes mediaId, we check that.
    String toStringResult = info.toString();
    assert toStringResult != null && toStringResult.contains(testMediaId) : "mediaId was not set correctly";
}
}
