// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagInfoFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:14:28 GMT 2024
 */
package org.jinstagram.entity.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagInfoFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagInfoFeed_ESTest extends TagInfoFeed_ESTest_scaffolding {
@Test
public void testGetMeta() {
    TagInfoFeed tagInfoFeed = new TagInfoFeed();
    Meta expectedMeta = new Meta();
    tagInfoFeed.setMeta(expectedMeta);

    Meta actualMeta = tagInfoFeed.getMeta();

    // Verify that the returned Meta object is the same as the one set
    org.junit.Assert.assertEquals(expectedMeta, actualMeta);
}
}
