// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/UserInfo_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:22:05 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.users.basicinfo.UserInfo;
import org.jinstagram.entity.users.basicinfo.UserInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserInfo_ESTest extends UserInfo_ESTest_scaffolding {
@Test
public void testToString() {
    UserInfo userInfo = new UserInfo();
    UserInfoData data = new UserInfoData();
    // Assuming UserInfoData has a suitable toString() method or override it for test
    data.setId("12345");
    data.setUsername("testuser");
    userInfo.setData(data);

    String expected = String.format("UserInfo [data=%s]", data.toString());
    String actual = userInfo.toString();

    org.junit.Assert.assertEquals(expected, actual);
}
}
