// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/JavaTimestampFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:44:18 GMT 2024
 */
package com.zappos.json.format;





import java.text.SimpleDateFormat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import com.zappos.json.formatter.JavaTimestampFormatter;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import com.zappos.json.ZapposJson;
import java.sql.Timestamp;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaTimestampFormatter;
import com.zappos.json.format.ValueFormatter;
import java.sql.Timestamp;
import java.text.ParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class JavaTimestampFormatter_ESTest extends JavaTimestampFormatter_ESTest_scaffolding {
    







    @Test
    public void testFormat_withPattern() {
        // Arrange
        ZapposJson zapposJson = mock(ZapposJson.class);
        Timestamp timestamp = new Timestamp(1590877273000L);
        String pattern = "yyyy-MM-dd HH:mm:ss";
        String expected = "2020-05-30 08:34:33";

        when(zapposJson.toJson(timestamp)).thenReturn(expected);

        JavaTimestampFormatter formatter = new JavaTimestampFormatter();
        formatter.setPattern(pattern);

        // Act
        String result = formatter.format(zapposJson, timestamp);

        // Assert
        assertEquals(expected, result);
    }
}
