// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/format/NoOpValueFormatter_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 13:46:01 GMT 2024
 */
package com.zappos.json.format;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.NoOpValueFormatter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class NoOpValueFormatter_ESTest extends NoOpValueFormatter_ESTest_scaffolding {
    
@Test
public void testCast() {
    // Arrange
    NoOpValueFormatter noOpValueFormatter = new NoOpValueFormatter();
    String inputString = "Test String";
    
    // Act
    Object result1 = noOpValueFormatter.cast(inputString);
    
    // Assert
    assertEquals(inputString, result1);
    
    // Arrange
    Integer inputInteger = 123;
    
    // Act
    Object result2 = noOpValueFormatter.cast(inputInteger);
    
    // Assert
    assertEquals(inputInteger, result2);
    
    // Arrange
    // CustomObject inputCustomObject = new CustomObject(); // Removed due to the error
    // Act
    // Object result3 = noOpValueFormatter.cast(inputCustomObject); // Removed due to the error
    // Assert
    // assertEquals(inputCustomObject, result3); // Removed due to the error
}
}
