// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/SubscriptionsListResponse_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:05:11 GMT 2024
 */
package org.jinstagram.realtime;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.realtime.SubscriptionsListResponse;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.realtime.SubscriptionsListResponse;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SubscriptionsListResponse_ESTest extends SubscriptionsListResponse_ESTest_scaffolding {


    
    @Test
    public void testSetMeta() {
        // Given
        Meta testMeta = new Meta();
        SubscriptionsListResponse subscriptionsListResponse = new SubscriptionsListResponse();

        // When
        subscriptionsListResponse.setMeta(testMeta);

        // Then
        assertEquals(testMeta, subscriptionsListResponse.getMeta());
    }


    
    @Test
    public void testSetMeta_1() {
        // Given
        Meta meta = new Meta();
        SubscriptionsListResponse subscriptionsListResponse = new SubscriptionsListResponse();

        // When
        subscriptionsListResponse.setMeta(meta);

        // Then
        assertEquals(meta, subscriptionsListResponse.getMeta());
    }

}
