// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/ProjectionProfile_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */
package technology.tabula;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {

    
    @Test
    public void testFilter() {
        float[] data = new float[] {0f, 1f, 0f, 1f, 0f, 1f, 0f};
        float alpha = 0.5f;
        float[] expected = new float[] {0f, 0.5f, 0.25f, 0.625f, 0.3125f, 0.65625f, 0.328125f};
        float[] result = ProjectionProfile.filter(data, alpha);
        assertEquals(expected.length, result.length);
        for (int i = 0; i < expected.length; i++) {
            assertEquals(expected[i], result[i], 1e-6);
        }

        float[] resultAlphaZero = ProjectionProfile.filter(data, 0f);
        for (int i = 0; i < data.length; i++) {
            assertEquals(data[0], resultAlphaZero[i], 1e-6);
        }
    }
}
