// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {
@Test
public void testGetPoints() {
    // Create a rectangle with known coordinates
    float top = 10f;
    float left = 20f;
    float width = 30f;
    float height = 40f;
    Rectangle rect = new Rectangle(top, left, width, height);

    // Get the points from the rectangle
    Point2D[] points = rect.getPoints();

    // Assert that there are exactly 4 points
    org.junit.Assert.assertNotNull(points);
    org.junit.Assert.assertEquals(4, points.length);

    // Check the points are in clockwise order starting from top-left
    // top-left
    org.junit.Assert.assertEquals(left, points[0].getX(), 0.0001);
    org.junit.Assert.assertEquals(top, points[0].getY(), 0.0001);

    // top-right
    org.junit.Assert.assertEquals(left + width, points[1].getX(), 0.0001);
    org.junit.Assert.assertEquals(top, points[1].getY(), 0.0001);

    // bottom-right
    org.junit.Assert.assertEquals(left + width, points[2].getX(), 0.0001);
    org.junit.Assert.assertEquals(top + height, points[2].getY(), 0.0001);

    // bottom-left
    org.junit.Assert.assertEquals(left, points[3].getX(), 0.0001);
    org.junit.Assert.assertEquals(top + height, points[3].getY(), 0.0001);
}
}
