// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;






import java.util.Arrays;
import java.util.ArrayList;
import java.awt.Rectangle;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {

    
    





@Test
public void testSetTextElements_ReplacesTextElements() {
    // Arrange:
    // Create a subclass of RectangularTextContainer to make it instantiable and specify T as String for test simplicity
    class TestRectangularTextContainer extends RectangularTextContainer<String> {
        public TestRectangularTextContainer(float top, float left, float width, float height) {
            super(top, left, width, height);
        }
    }
    TestRectangularTextContainer container = new TestRectangularTextContainer(0, 0, 10, 10);
    List<String> initialElements = List.of("Initial1", "Initial2");
    container.textElements = new ArrayList<>(initialElements);

    List<String> newElements = List.of("New1", "New2", "New3");

    // Act:
    container.setTextElements(newElements);

    // Assert:
    assertEquals(newElements, container.textElements, "The textElements list should be replaced with the new list");
}
}
