// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;






import java.awt.geom.Rectangle2D;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {

    @Test
    public void testCropRulingsToArea() {
        Rectangle2D area = new Rectangle2D.Float(10, 10, 30, 30);
        List<Ruling> rulings = new LinkedList<>();
        rulings.add(new Ruling(15, 15, 10, 0)); 
        rulings.add(new Ruling(20, 20, 0, 5));  
        rulings.add(new Ruling(5, 5, 20, 0));   
        rulings.add(new Ruling(35, 25, 0, 20)); 
        rulings.add(new Ruling(0, 0, 5, 0));    
        rulings.add(new Ruling(50, 50, 0, 10)); 
        List<Ruling> cropped = Ruling.cropRulingsToArea(rulings, area);
       
}
}