// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/SpreadsheetExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:51:32 GMT 2024
 */
package technology.tabula.extractors;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import java.awt.geom.Point2D;
import java.awt.Rectangle;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.Page;
import technology.tabula.Rectangle;
import technology.tabula.Ruling;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SpreadsheetExtractionAlgorithm_ESTest extends SpreadsheetExtractionAlgorithm_ESTest_scaffolding {
    






@Test
public void testFindSpreadsheetsFromCells() {
    // The test is meant to verify that the SpreadsheetExtractionAlgorithm.findSpreadsheetsFromCells method correctly identifies and extracts spreadsheet rectangles from a collection of cell rectangles.

    // Arrange
    List<Rectangle> cells = new ArrayList<>();
    cells.add(new Rectangle(0, 0, 2, 2));
    cells.add(new Rectangle(1, 1, 3, 3));

    // Act
    List<Rectangle> result = SpreadsheetExtractionAlgorithm.findSpreadsheetsFromCells(cells);

    // Assert
    Assert.assertEquals(1, result.size());
    Assert.assertEquals(new Rectangle(0, 0, 3, 3), result.get(0));
}
}
