// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {
@Test
public void testVerticallyOverlaps() {
    // Create two rectangles that vertically overlap
    Rectangle r1 = new Rectangle(10, 0, 5, 10); // top=10, left=0, width=5, height=10 (bottom=20)
    Rectangle r2 = new Rectangle(15, 2, 5, 10); // top=15, left=2, width=5, height=10 (bottom=25)
    // They overlap vertically between 15 and 20

    // Should return true because vertical overlap > 0
    assert r1.verticallyOverlaps(r2);

    // Create two rectangles that do not vertically overlap
    Rectangle r3 = new Rectangle(0, 0, 5, 5);   // top=0, bottom=5
    Rectangle r4 = new Rectangle(6, 0, 5, 5);   // top=6, bottom=11

    // Should return false because vertical overlap = 0
    assert !r3.verticallyOverlaps(r4);

    // Create two rectangles that just touch at the edge (bottom of r3 == top of r4)
    Rectangle r5 = new Rectangle(0, 0, 5, 5);   // top=0, bottom=5
    Rectangle r6 = new Rectangle(5, 0, 5, 5);   // top=5, bottom=10

    // Should return false because vertical overlap = 0 (edges only)
    assert !r5.verticallyOverlaps(r6);
}
}
