// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
@Test
public void testEquals() {
    // Create some TextElements for testing
    TextElement te1 = new TextElement("A", 10f, 20f, 5f, 7f);
    TextElement te2 = new TextElement("B", 10f, 25f, 5f, 7f);
    TextElement te3 = new TextElement("C", 10f, 30f, 5f, 7f);

    // Create TextChunk instances
    TextChunk chunk1 = new TextChunk(te1);
    TextChunk chunk2 = new TextChunk(te1);
    TextChunk chunk3 = new TextChunk(te2);
    TextChunk chunk4 = new TextChunk(List.of(te1, te2));
    TextChunk chunk5 = new TextChunk(List.of(te1, te2));
    TextChunk chunk6 = new TextChunk(List.of(te1, te3));

    // Reflexive: chunk1 should equal itself
    assertTrue(chunk1.equals(chunk1));

    // Symmetric: chunk1 equals chunk2 and vice versa
    assertTrue(chunk1.equals(chunk2));
    assertTrue(chunk2.equals(chunk1));

    // Different textElements: chunk1 and chunk3 should not be equal
    assertFalse(chunk1.equals(chunk3));

    // Different number of textElements: chunk1 and chunk4 should not be equal
    assertFalse(chunk1.equals(chunk4));

    // Same list of textElements: chunk4 and chunk5 should be equal
    assertTrue(chunk4.equals(chunk5));
    assertTrue(chunk5.equals(chunk4));

    // Different textElements in list: chunk4 and chunk6 should not be equal
    assertFalse(chunk4.equals(chunk6));

    // Null comparison: chunk1 should not equal null
    assertFalse(chunk1.equals(null));

    // Different class object: chunk1 should not equal a String
    assertFalse(chunk1.equals("some string"));
}
}
