// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/likes/LikesFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:59:43 GMT 2024
 */
package org.jinstagram.entity.likes;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.likes.LikesFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LikesFeed_ESTest extends LikesFeed_ESTest_scaffolding {
    @Test
    public void testToString() {
        LikesFeed likesFeed = new LikesFeed();
        Meta meta = new Meta();
        meta.setSomeInfo("Some meta info");
        likesFeed.setMeta(meta);
        
        List<User> userList = new ArrayList<>();
        User user1 = new User();
        user1.setName("User 1");
        userList.add(user1);
        User user2 = new User();
        user2.setName("User 2");
        userList.add(user2);
        likesFeed.setUserList(userList);
        
        String expected = "LikesFeed [meta=Meta{someInfo='Some meta info'}, userList=[User{name='User 1'}, User{name='User 2'}]]";
        String actual = likesFeed.toString();
        
        assertEquals(expected, actual);
    }
}
