// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
    @Test
    public void testGetSortedKeys() {
        // Given
        Map<String, String> testMap = new HashMap<>();
        testMap.put("b", "value2");
        testMap.put("a", "value1");
        testMap.put("c", "value3");

        // When
        List<String> sortedKeys = MapUtils.getSortedKeys(testMap);

        // Then
        assertEquals(3, sortedKeys.size());
        assertEquals("a", sortedKeys.get(0));
        assertEquals("b", sortedKeys.get(1));
        assertEquals("c", sortedKeys.get(2));
    }
}
