// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/http/Request_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:43:07 GMT 2024
 */
package org.jinstagram.http;
import static org.junit.Assert.*;
import org.junit.Test;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.Proxy;
import java.net.URL;
import java.net.URLStreamHandler;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jinstagram.http.Request;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Request_ESTest extends Request_ESTest_scaffolding {
    @Test
    public void testAddHeaders() {
        // Create a mock HttpURLConnection object
        HttpURLConnection mockConnection = new MockHttpURLConnection();

        // Create a Request object
        Request request = new Request(Verbs.GET, "http://example.com");
        request.addHeader("Content-Type", "application/json");
        request.addHeader("Authorization", "Bearer token");

        // Call the method under test
        request.addHeaders(mockConnection);

        // Verify that the headers are set correctly in the HttpURLConnection object
        assertEquals("application/json", mockConnection.getRequestProperty("Content-Type"));
        assertEquals("Bearer token", mockConnection.getRequestProperty("Authorization"));
    }
}
