// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:18:17 GMT 2024
 */
package org.jinstagram.entity.tags;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagSearchFeed_ESTest extends TagSearchFeed_ESTest_scaffolding {
    @Test
    public void testGetTagList() {
        // Create a TagSearchFeed instance
        TagSearchFeed tagSearchFeed = new TagSearchFeed();
        
        // Create a list of TagInfoData objects
        List<TagInfoData> expectedTagList = new LinkedList<>();
        TagInfoData tagInfoData1 = new TagInfoData();
        TagInfoData tagInfoData2 = new TagInfoData();
        expectedTagList.add(tagInfoData1);
        expectedTagList.add(tagInfoData2);
        
        // Set the tagList field in the TagSearchFeed instance
        tagSearchFeed.setTagList(expectedTagList);
        
        // Retrieve the tagList using getTagList() method
        List<TagInfoData> actualTagList = tagSearchFeed.getTagList();
        
        // Check if the retrieved tagList is not null
        assertNotNull(actualTagList);
        
        // Check if the retrieved tagList size matches the expected size
        assertEquals(expectedTagList.size(), actualTagList.size());
        
        // Check if the retrieved tagList contains the expected TagInfoData objects
        for (int i = 0; i < expectedTagList.size(); i++) {
            assertEquals(expectedTagList.get(i), actualTagList.get(i));
        }
    }
}
