// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/UserFeedData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:34:30 GMT 2024
 */
package org.jinstagram.entity.users.feed;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.feed.UserFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserFeedData_ESTest extends UserFeedData_ESTest_scaffolding {
    @Test
    public void testSetLastName() {
        UserFeedData userFeedData = new UserFeedData();
        String lastName = "Doe";
        
        // Setting last name using deprecated method
        userFeedData.setLastName(lastName);
        
        // Retrieving last name to verify if it was set correctly
        String retrievedLastName = userFeedData.getLastName();
        
        // Asserting that the retrieved last name matches the one set
        assertEquals(lastName, retrievedLastName);
    }
}
