// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/UsersInPhoto_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:53:50 GMT 2024
 */
package org.jinstagram.entity.common;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.GridPosition;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.common.UsersInPhoto;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UsersInPhoto_ESTest extends UsersInPhoto_ESTest_scaffolding {
    @Test
    public void testGetUser() {
        // Create a UsersInPhoto instance
        UsersInPhoto usersInPhoto = new UsersInPhoto();
        
        // Create a User instance to set as the user in UsersInPhoto
        User expectedUser = new User();
        expectedUser.setUsername("testUser");
        usersInPhoto.setUser(expectedUser);
        
        // Retrieve the user using getUser() method
        User actualUser = usersInPhoto.getUser();
        
        // Assert that the retrieved user is the same as the one set
        assertEquals(expectedUser, actualUser);
    }
}
