// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Comments_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:36:05 GMT 2024
 */
package org.jinstagram.entity.common;



import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import org.jinstagram.entity.comments.Comments;
import org.jinstagram.entity.comments.FromTagData;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.Comments;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Comments_ESTest extends Comments_ESTest_scaffolding {
    
    

    



@Test
public void testSetComments() {
    // Arrange:
    Comments comments = new Comments();
    List<CommentData> newComments = new ArrayList<>();
    CommentData comment1 = new CommentData();
    comment1.setCreatedTime("2022-01-01");
    comment1.setText("Great post!");
    comment1.setId("1");
    CommentData comment2 = new CommentData();
    comment2.setCreatedTime("2022-01-02");
    comment2.setText("Awesome content!");
    comment2.setId("2");
    newComments.add(comment1);
    newComments.add(comment2);

    // Act:
    comments.setComments(newComments);

    // Assert:
    List<CommentData> updatedComments = comments.getComments();
    assertEquals(2, updatedComments.size());
    assertEquals("2022-01-01", updatedComments.get(0).getCreatedTime());
    assertEquals("Great post!", updatedComments.get(0).getText());
    assertEquals("1", updatedComments.get(0).getId());
    assertEquals("2022-01-02", updatedComments.get(1).getCreatedTime());
    assertEquals("Awesome content!", updatedComments.get(1).getText());
    assertEquals("2", updatedComments.get(1).getId());
}
}
