// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/likes/LikesFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:59:43 GMT 2024
 */
package org.jinstagram.entity.likes;




import java.util.ArrayList;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.likes.LikesFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LikesFeed_ESTest extends LikesFeed_ESTest_scaffolding {
    


    


@Test
public class LikesFeedTest {

    // Arrange:
    Meta meta = new Meta();
    meta.setCode(200);
    meta.setErrorType("Success");
    meta.setErrorMessage("No errors");

    User user1 = new User();
    user1.setId("1");
    user1.setUsername("user1");

    User user2 = new User();
    user2.setId("2");
    user2.setUsername("user2");

    List<User> userList = new ArrayList<>();
    userList.add(user1);
    userList.add(user2);

    LikesFeed likesFeed = new LikesFeed();
    likesFeed.setMeta(meta);
    likesFeed.setUserList(userList);

    // Act:
    String result = likesFeed.toString();

    // Assert:
    assertEquals("LikesFeed [meta=Meta{code=200, errorType='Success', errorMessage='No errors'}, userList=[User{id='1', username='user1'}, User{id='2', username='user2'}]", result);
}
}
