// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;


import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
    
    

    

@Test
public void testSort() {
    // Arrange
    Map<String, String> unsortedMap = new LinkedHashMap<>();
    unsortedMap.put("C", "Charlie");
    unsortedMap.put("A", "Alpha");
    unsortedMap.put("B", "Bravo");

    List<String> expectedSortedKeys = new ArrayList<>();
    expectedSortedKeys.add("A");
    expectedSortedKeys.add("B");
    expectedSortedKeys.add("C");

    // Act
    Map<String, String> sortedMap = MapUtils.sort(unsortedMap);
    List<String> actualSortedKeys = new ArrayList<>(sortedMap.keySet());

    // Assert
    assertEquals(expectedSortedKeys, actualSortedKeys);
    assertEquals("Alpha", sortedMap.get("A"));
    assertEquals("Bravo", sortedMap.get("B"));
    assertEquals("Charlie", sortedMap.get("C"));
}
}
