// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/likes/LikesFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:59:43 GMT 2024
 */
package org.jinstagram.entity.likes;

// Import: (No unnecessary import statements in the code)
import java.util.ArrayList;
import org.mockito.Mock;
import org.mockito.InjectMocks;
import org.jinstagram.entity.common.LikesFeed;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.LinkedList;
import java.util.List;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.likes.LikesFeed;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.likes.LikesFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LikesFeed_ESTest extends LikesFeed_ESTest_scaffolding {
    
    
    



@Test
public void testSetUserList() {
    // Arrange
    LikesFeed likesFeed = new LikesFeed();
    List<User> userList = new ArrayList<>();
    
    User user1 = new User();
    user1.setUserName("user1");
    user1.setFullName("User One");
    user1.setProfilePictureUrl("url1");
    user1.setBio("Bio One");
    user1.setWebsiteUrl("website1");
    user1.setId("1");
    
    User user2 = new User();
    user2.setUserName("user2");
    user2.setFullName("User Two");
    user2.setProfilePictureUrl("url2");
    user2.setBio("Bio Two");
    user2.setWebsiteUrl("website2");
    user2.setId("2");

    userList.add(user1);
    userList.add(user2);

    // Act
    likesFeed.setUserList(userList);

    // Assert
    assertEquals(2, likesFeed.getUserList().size());
    assertEquals("user1", likesFeed.getUserList().get(0).getUserName());
    assertEquals("User One", likesFeed.getUserList().get(0).getFullName());
    assertEquals("url1", likesFeed.getUserList().get(0).getProfilePictureUrl());
    assertEquals("Bio One", likesFeed.getUserList().get(0).getBio());
    assertEquals("website1", likesFeed.getUserList().get(0).getWebsiteUrl());
    assertEquals("1", likesFeed.getUserList().get(0).getId());

    assertEquals("user2", likesFeed.getUserList().get(1).getUserName());
    assertEquals("User Two", likesFeed.getUserList().get(1).getFullName());
    assertEquals("url2", likesFeed.getUserList().get(1).getProfilePictureUrl());
    assertEquals("Bio Two", likesFeed.getUserList().get(1).getBio());
    assertEquals("website2", likesFeed.getUserList().get(1).getWebsiteUrl());
    assertEquals("2", likesFeed.getUserList().get(1).getId());
}
}
