// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Pagination_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:50:55 GMT 2024
 */
package org.jinstagram.entity.common;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Pagination;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Pagination_ESTest extends Pagination_ESTest_scaffolding {
    
@Test
public void testToString() {
    // Arrange
    Pagination pagination = new Pagination();
    pagination.setDepreciationWarning("Depreciation warning message");
    pagination.setMinTagId("1");
    pagination.setNextMaxId("10");
    pagination.setNextMaxTagId("20");
    pagination.setNextMinId("5");
    pagination.setNextUrl("https://example.com");

    // Act
    String result = pagination.toString();

    // Assert
    assertEquals("Pagination [depreciationWarning=Depreciation warning message, minTagId=1, nextMaxId=10, nextMaxTagId=20, nextMinId=5, nextUrl=https://example.com]", result);
}
}
