// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Images_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:42:55 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.ImageData;
import org.jinstagram.entity.common.Images;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Images_ESTest extends Images_ESTest_scaffolding {
@Test
public void testSetLowResolution() {
    Images images = new Images();
    ImageData lowResData = new ImageData();
    // Optionally set some properties on lowResData if available, e.g. lowResData.setUrl("http://example.com/lowres.jpg");

    images.setLowResolution(lowResData);

    // Verify that the lowResolution field was updated correctly by using the getter
    ImageData result = images.getLowResolution();
    org.junit.Assert.assertNotNull("Low resolution image data should not be null after setting", result);
    org.junit.Assert.assertEquals("The low resolution image data should be the same as set", lowResData, result);
}
}
