// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;


import org.scribe.model.Parameter;
import org.mockito.Mockito;
import static org.mockito.Mockito.*;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Token;
import org.scribe.model.Verb;
import org.scribe.model.OAuthConstants;
import org.scribe.oauth.OAuthConfig;
import org.jinstagram.auth.Token;
import org.jinstagram.auth.OAuthRequest;
import org.jinstagram.auth.OAuthConstants;
import org.jinstagram.auth.OAuthConfig;
import org.jinstagram.auth.InstagramService;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {

    
    
    
    
    
    @Test
    public void signRequest_shouldAddAccessTokenAsQueryParameter() {
        // Arrange:
        InstagramApi api = new InstagramApi() {
            @Override
            public String getAccessTokenEndpoint() {
                return null;
            }

            @Override
            public Verbs getAccessTokenVerb() {
                return null;
            }

            @Override
            public String getAuthorizationUrl(OAuthConfig config) {
                return null;
            }

            @Override
            public AccessTokenExtractor getAccessTokenExtractor() {
                return null;
            }

            @Override
            public InstagramService createService(OAuthConfig config) {
                return null;
            }
        };
        OAuthConfig config = new OAuthConfig();
        InstagramService service = new InstagramService(api, config);

        String tokenValue = "testAccessToken";
        Token token = new Token(tokenValue, "secret");

        OAuthRequest request = new OAuthRequest(Verb.GET, "http://example.com/api");

        // Act:
        service.signRequest(token, request);

        // Assert:
        // Check that the request has the access token as a query string parameter
        List<Parameter> params = request.getQueryStringParams();
        boolean found = false;
        for (Parameter param : params) {
            if (OAuthConstants.ACCESS_TOKEN.equals(param.getKey()) && tokenValue.equals(param.getValue())) {
                found = true;
                break;
            }
        }
        assertTrue(found, "The access token should be added as a query string parameter.");
    }
}
