// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;







import org.scribe.builder.api.InstagramApi;
import org.scribe.model.OAuthConfig;
import org.scribe.oauth.OAuthService;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {
@Test(expected = UnsupportedOperationException.class)
public void testGetRequestToken_throwsUnsupportedOperationException() {
    InstagramApi api = new InstagramApi();
    OAuthConfig config = new OAuthConfig("clientId", "clientSecret", "callback");
    InstagramService service = new InstagramService(api, config);

    // This should throw UnsupportedOperationException
    service.getRequestToken();
}
}

    @Test(expected = UnsupportedOperationException.class)
    public void testGetRequestToken_throwsUnsupportedOperationException() {
        InstagramApi api = new InstagramApi();

        OAuthConfig config = new OAuthConfig("clientId", "clientSecret");
        config.setCallback("callback");

        InstagramService service = new InstagramService(api, config);
        service.getRequestToken();
    }
}






@Test
public void getRequestToken_shouldThrowUnsupportedOperationException() {
    // Arrange:
    InstagramApi api = new InstagramApi() {
        // Minimal stub implementation, if InstagramApi is an interface or abstract class
    };
    OAuthConfig config = new OAuthConfig();
    InstagramService service = new InstagramService(api, config);

    // Act & Assert:
    UnsupportedOperationException exception = assertThrows(UnsupportedOperationException.class, service::getRequestToken);
    // Assert the exception message is as expected
    org.junit.jupiter.api.Assertions.assertEquals(
        "Unsupported operation, please use 'getAuthorizationUrl' and redirect your users there",
        exception.getMessage()
    );
}
}
