// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/auth/oauth/InstagramService_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:26:33 GMT 2024
 */
package org.jinstagram.auth.oauth;


import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.jinstagram.auth.extractors.TokenExtractor;
import org.jinstagram.auth.oauth.InstagramApi;
import org.jinstagram.auth.oauth.OAuthConfig;
import org.jinstagram.auth.oauth.OAuthConstants;
import org.jinstagram.auth.oauth.OAuthRequest;
import org.jinstagram.auth.oauth.Verifier;
import org.jinstagram.auth.oauth.Verb;
import org.mockito.Mockito;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.auth.InstagramApi;
import org.jinstagram.auth.model.OAuthConfig;
import org.jinstagram.auth.model.OAuthRequest;
import org.jinstagram.auth.model.Token;
import org.jinstagram.auth.model.Verifier;
import org.jinstagram.auth.oauth.InstagramService;
import org.jinstagram.http.Verbs;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramService_ESTest extends InstagramService_ESTest_scaffolding {


    


    
    @Test
    public void testGetAccessToken_successfulResponse_extractsToken() throws IOException {
        // Arrange:
        InstagramApi mockApi = mock(InstagramApi.class);
        OAuthConfig mockConfig = mock(OAuthConfig.class);
        Verifier verifier = new Verifier("auth-code-123");
        OAuthRequest mockRequest = mock(OAuthRequest.class);
        Response mockResponse = mock(Response.class);
        AccessTokenExtractor mockExtractor = mock(AccessTokenExtractor.class);
        Token expectedToken = new Token("access-token", "secret");

        // Mock config getters
        when(mockConfig.getApiKey()).thenReturn("api-key");
        when(mockConfig.getApiSecret()).thenReturn("api-secret");
        when(mockConfig.getCallback()).thenReturn("http://callback.url");
        when(mockConfig.hasScope()).thenReturn(true);
        when(mockConfig.getScope()).thenReturn("user_profile");
        when(mockConfig.getDisplay()).thenReturn("popup");
        when(mockConfig.getRequestProxy()).thenReturn(null);

        // Mock API methods
        when(mockApi.getAccessTokenVerb()).thenReturn("POST");
        when(mockApi.getAccessTokenEndpoint()).thenReturn("http://access.token.endpoint");
        when(mockApi.getAccessTokenExtractor()).thenReturn(mockExtractor);

        // Mock request send() and response body
        when(mockRequest.send()).thenReturn(mockResponse);
        when(mockResponse.getBody()).thenReturn("{ \"access_token\": \"access-token\" }");
        when(mockExtractor.extract(anyString())).thenReturn(expectedToken);

        // Create test subclass to override OAuthRequest creation
        class TestInstagramService extends InstagramService {
            public TestInstagramService(InstagramApi api, OAuthConfig config) {
                super(api, config);
            }
            @Override
            protected OAuthRequest createOAuthRequest(String verb, String url) {
                assertEquals("POST", verb);
                assertEquals("http://access.token.endpoint", url);
                return mockRequest;
            }
        }

        InstagramService service = new TestInstagramService(mockApi, mockConfig);

        // Act:
        Token actualToken = service.getAccessToken(verifier);

        // Assert:
        assertNotNull(actualToken);
        assertEquals(expectedToken, actualToken);

        // Verify body parameters set correctly
        verify(mockRequest).addBodyParameter(OAuthConstants.CLIENT_ID, "api-key");
        verify(mockRequest).addBodyParameter(OAuthConstants.CLIENT_SECRET, "api-secret");
        verify(mockRequest).addBodyParameter(OAuthConstants.GRANT_TYPE, "authorization_code");
        verify(mockRequest).addBodyParameter(OAuthConstants.CODE, "auth-code-123");
        verify(mockRequest).addBodyParameter(OAuthConstants.REDIRECT_URI, "http://callback.url");
        verify(mockRequest).addBodyParameter(OAuthConstants.SCOPE, "user_profile");
        verify(mockRequest).addBodyParameter(OAuthConstants.DISPLAY, "popup");
        verify(mockRequest, never()).setProxy(any());

        verify(mockRequest).send();
        verify(mockExtractor).extract(mockResponse.getBody());
    }
}
