// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/CarouselMedia_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:26:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;




import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.List;
import org.mockito.Mockito;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CarouselMedia_ESTest extends CarouselMedia_ESTest_scaffolding {
    


    
    
    
    @Test
    public void testSetUsersInPhotoList() {
        // Create a CarouselMedia object
        CarouselMedia carouselMedia = new CarouselMedia();

        // Create a list of UsersInPhoto
        List<UsersInPhoto> usersInPhotoList = new ArrayList<>();

        // Create UsersInPhoto objects
        UsersInPhoto user1 = new UsersInPhoto();
        user1.setUser(new User("user1"));
        user1.setPosition(new GridPosition(1, 1));

        UsersInPhoto user2 = new UsersInPhoto();
        user2.setUser(new User("user2"));
        user2.setPosition(new GridPosition(2, 2));

        // Add UsersInPhoto objects to the list
        usersInPhotoList.add(user1);
        usersInPhotoList.add(user2);

        // Set the list of UsersInPhoto to the CarouselMedia object
        carouselMedia.setUsersInPhotoList(usersInPhotoList);

        // Verify that the list of UsersInPhoto has been set correctly
        assertEquals(usersInPhotoList, carouselMedia.getUsersInPhotoList());
    }
}
