// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/ImageData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:40:48 GMT 2024
 */
package org.jinstagram.entity.common;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.ImageData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ImageData_ESTest extends ImageData_ESTest_scaffolding {
    
    @Test
    public void testSetImageHeight() {
        ImageData imageData = new ImageData();
        
        // Test setting positive height
        int positiveHeight = 100;
        imageData.setImageHeight(positiveHeight);
        assertEquals(positiveHeight, imageData.getImageHeight());
        
        // Test setting zero height
        int zeroHeight = 0;
        imageData.setImageHeight(zeroHeight);
        assertEquals(zeroHeight, imageData.getImageHeight());
        
        // Test setting negative height
        int negativeHeight = -50;
        imageData.setImageHeight(negativeHeight);
        assertEquals(negativeHeight, imageData.getImageHeight());
    }
}
