// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;





import java.util.Arrays;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {

    
    


    

@Test
    public void merge(RectangularTextContainer<String> other) {
        // Simulate super.merge by updating bounding rectangle to encompass both
        if (!(other instanceof TestRectangularTextContainer)) {
            return;
        }
        TestRectangularTextContainer o = (TestRectangularTextContainer) other;
        float newTop = Math.min(this.top, o.top);
        float newLeft = Math.min(this.left, o.left);
        float right = Math.max(this.left + this.width, o.left + o.width);
        float bottom = Math.max(this.top + this.height, o.top + o.height);
        this.top = newTop;
        this.left = newLeft;
        this.width = right - newLeft;
        this.height = bottom - newTop;
    }
}
