// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/SpreadsheetExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:51:32 GMT 2024
 */
package technology.tabula.extractors;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.Page;
import technology.tabula.Rectangle;
import technology.tabula.Ruling;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SpreadsheetExtractionAlgorithm_ESTest extends SpreadsheetExtractionAlgorithm_ESTest_scaffolding {

    @Test
    public void testFindCells_basicGrid() {
        List<Ruling> horizontalRulings = new LinkedList<>();
        horizontalRulings.add(new Ruling(0, 0, 20, 0));   
        horizontalRulings.add(new Ruling(0, 10, 20, 10)); 
        horizontalRulings.add(new Ruling(0, 20, 20, 20)); 
        
        List<Ruling> verticalRulings = new LinkedList<>();
        verticalRulings.add(new Ruling(0, 0, 0, 20));   
        verticalRulings.add(new Ruling(10, 0, 10, 20)); 
        verticalRulings.add(new Ruling(20, 0, 20, 20)); 
        
        List<Cell> cells = SpreadsheetExtractionAlgorithm.findCells(horizontalRulings, verticalRulings);
        
        // Verify the expected number of cells only, since position accessors do not exist
        assertEquals(4, cells.size());
    }
}
