// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Table_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:11:53 GMT 2024
 */
package technology.tabula;





import static org.mockito.Mockito.*;
import technology.tabula.*;
import java.util.List;
import technology.tabula.Page;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.RectangularTextContainer;
import technology.tabula.Table;
import technology.tabula.extractors.ExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Table_ESTest extends Table_ESTest_scaffolding {

    
    
    
    
    
    
    @Test
    public void testGetExtractionMethod_ReturnsCorrectExtractionMethodString() {
        // Arrange:
        ExtractionAlgorithm algorithm = new ExtractionAlgorithm("SampleAlgorithm");
        Table table = new Table(algorithm);

        // Act:
        String extractionMethod = table.getExtractionMethod();

        // Assert:
        assertEquals("SampleAlgorithm", extractionMethod);
    }
}
