// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;




import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.parser.TextElement;
import com.itextpdf.text.pdf.parser.TextChunk;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {

    


@Test
public void testGetTextWithUseLineReturnsIgnoresParameter() {
    // Arrange:
    // Define a minimal TextElement class for testing purposes
    class TextElement {
        float x, y, width, height;
        String text;

        TextElement(float y, float x, float width, float height, String text) {
            this.x = x;
            this.y = y;
            this.width = width;
            this.height = height;
            this.text = text;
        }

        @Override
        public String toString() {
            return text;
        }
    }

    // Define a subclass of TextChunk that supports add() and getText()
    class TestTextChunk extends TextChunk {
        private final List<TextElement> elements = new ArrayList<>();

        public TestTextChunk(List<TextElement> textElements) {
            super(textElements);
            elements.addAll(textElements);
        }

        @Override
        public void add(TextElement e) {
            elements.add(e);
        }

        @Override
        public String getText() {
            StringBuilder sb = new StringBuilder();
            for (TextElement e : elements) {
                sb.append(e.text);
            }
            return sb.toString();
        }
    }

    List<TextElement> elements = new ArrayList<>();
    elements.add(new TextElement(0, 0, 10, 10, "Hello"));
    elements.add(new TextElement(0, 10, 10, 10, " "));
    elements.add(new TextElement(0, 20, 10, 10, "World"));

    TestTextChunk textChunk = new TestTextChunk(elements);

    // Act:
    String textWithTrue = textChunk.getText(true);
    String textWithFalse = textChunk.getText(false);
    String textDefault = textChunk.getText();

    // Assert:
    assertEquals(textDefault, textWithTrue, "getText(true) should return same as getText()");
    assertEquals(textDefault, textWithFalse, "getText(false) should return same as getText()");
}
}
