// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/BasicExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:49:38 GMT 2024
 */
package technology.tabula.extractors;
import org.junit.Test;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Page;
import technology.tabula.Ruling;
import technology.tabula.TextChunk;
import technology.tabula.extractors.BasicExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class BasicExtractionAlgorithm_ESTest extends BasicExtractionAlgorithm_ESTest_scaffolding {
    @Test
    public void testColumnPositions() {
        // Create sample data for testing
        List<Line> lines = new ArrayList<>();
        Line line1 = new Line();
        line1.addTextElement(new TextChunk(10, 20, 30, 40, "Text1"));
        line1.addTextElement(new TextChunk(50, 60, 70, 80, "Text2"));
        lines.add(line1);

        Line line2 = new Line();
        line2.addTextElement(new TextChunk(15, 25, 35, 45, "Text3"));
        line2.addTextElement(new TextChunk(55, 65, 75, 85, "Text4"));
        lines.add(line2);

        // Call the method to test
        List<Float> columnPositions = BasicExtractionAlgorithm.columnPositions(lines);

        // Assert the expected results
        List<Float> expectedColumnPositions = new ArrayList<>();
        expectedColumnPositions.add(30.0f);
        expectedColumnPositions.add(70.0f);
        Collections.sort(expectedColumnPositions);

        Collections.sort(columnPositions);
        assertEquals(expectedColumnPositions, columnPositions);
    }
}
