// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
    
    
    



    
@Test
public void testMerge() {
    // Arrange
    RectangularTextContainer<String> container1 = new RectangularTextContainer<>(10.0f, 20.0f, 100.0f, 50.0f);
    List<String> textElements1 = new ArrayList<>();
    textElements1.add("Text Element 1");
    textElements1.add("Text Element 2");
    container1.getTextElements().addAll(textElements1);

    RectangularTextContainer<String> container2 = new RectangularTextContainer<>(5.0f, 15.0f, 80.0f, 40.0f);
    List<String> textElements2 = new ArrayList<>();
    textElements2.add("Text Element 3");
    textElements2.add("Text Element 4");
    container2.getTextElements().addAll(textElements2);

    // Act
    RectangularTextContainer<String> mergedContainer = container1.merge(container2);

    // Assert
    assertEquals(4, mergedContainer.getTextElements().size());
    assertEquals("Text Element 3", mergedContainer.getTextElements().get(0));
    assertEquals("Text Element 4", mergedContainer.getTextElements().get(1));
    assertEquals("Text Element 1", mergedContainer.getTextElements().get(2));
    assertEquals("Text Element 2", mergedContainer.getTextElements().get(3));
}
}
