// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/EnforceSignedRequestUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:11:49 GMT 2024
 */
package org.jinstagram.utils;



import java.nio.charset.Charset;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.apache.commons.codec.binary.Hex;
import org.apache.commons.lang3.StringUtils;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.EnforceSignedRequestUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class EnforceSignedRequestUtils_ESTest extends EnforceSignedRequestUtils_ESTest_scaffolding {
    
    
    



@Test
public void testSignatureGeneration() throws InstagramException {
    // Arrange
    String endpoint = "/api/endpoint";
    Map<String, String> params = Map.of("param1", "value1", "param2", "value2");
    String clientSecret = "myClientSecret";
    String expectedSignature = "e7ff8b2d0b3b3b0b1a1d1c1f1e1a1b0d0a0b1a1c1d1e1f0b1c1d1e1f0a1b1c1d1e1f";

    // Act
    String actualSignature = EnforceSignedRequestUtils.signature(endpoint, params, clientSecret);

    // Assert
    assertEquals(expectedSignature, actualSignature);
}
}
