// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Likes_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:44:44 GMT 2024
 */
package org.jinstagram.entity.common;




import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Likes;
import org.jinstagram.entity.common.User;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Likes_ESTest extends Likes_ESTest_scaffolding {
    
    




@Test
public void testSetLikesUserList() {
    // Arrange
    Likes likes = new Likes();
    List<User> users = new ArrayList<>();
    User user1 = new User();
    user1.setId("1");
    user1.setUserName("user1");
    user1.setFullName("User One");
    user1.setProfilePictureUrl("url1");
    user1.setBio("Bio 1");
    user1.setWebsiteUrl("www.user1.com");

    User user2 = new User();
    user2.setId("2");
    user2.setUserName("user2");
    user2.setFullName("User Two");
    user2.setProfilePictureUrl("url2");
    user2.setBio("Bio 2");
    user2.setWebsiteUrl("www.user2.com");

    users.add(user1);
    users.add(user2);

    // Act
    likes.setLikesUserList(users);

    // Assert
    assertEquals(2, likes.getLikesUserList().size());
    assertEquals("1", likes.getLikesUserList().get(0).getId());
    assertEquals("user1", likes.getLikesUserList().get(0).getUserName());
    assertEquals("User One", likes.getLikesUserList().get(0).getFullName());
    assertEquals("url1", likes.getLikesUserList().get(0).getProfilePictureUrl());
    assertEquals("Bio 1", likes.getLikesUserList().get(0).getBio());
    assertEquals("www.user1.com", likes.getLikesUserList().get(0).getWebsiteUrl());

    assertEquals("2", likes.getLikesUserList().get(1).getId());
    assertEquals("user2", likes.getLikesUserList().get(1).getUserName());
    assertEquals("User Two", likes.getLikesUserList().get(1).getFullName());
    assertEquals("url2", likes.getLikesUserList().get(1).getProfilePictureUrl());
    assertEquals("Bio 2", likes.getLikesUserList().get(1).getBio());
    assertEquals("www.user2.com", likes.getLikesUserList().get(1).getWebsiteUrl());
}
}
