// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/MediaFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:28:18 GMT 2024
 */
package org.jinstagram.entity.users.feed;



import java.util.ArrayList;
import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.common.Pagination;
import org.jinstagram.entity.users.feed.MediaFeed;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaFeed_ESTest extends MediaFeed_ESTest_scaffolding {
    
    




@Test
public void testToString() {
    // Arrange
    TagMediaFeed tagMediaFeed = new TagMediaFeed();
    List<MediaFeedData> testData = new ArrayList<>();
    testData.add(new MediaFeedData("test1"));
    testData.add(new MediaFeedData("test2"));
    tagMediaFeed.setData(testData);
    tagMediaFeed.setMeta(new Meta("testMeta"));
    tagMediaFeed.setPagination(new Pagination("testPagination"));

    // Act
    String result = tagMediaFeed.toString();

    // Assert
    assertNotNull(result);
    assertTrue(result.contains("TagMediaFeed"));
    assertTrue(result.contains("data=" + testData.toString()));
    assertTrue(result.contains("meta=testMeta"));
    assertTrue(result.contains("pagination=testPagination"));
}
}
