// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:18:17 GMT 2024
 */
package org.jinstagram.entity.tags;



import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import org.jinstagram.entity.common.TagInfoData;
import org.jinstagram.entity.common.TagSearchFeed;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagSearchFeed_ESTest extends TagSearchFeed_ESTest_scaffolding {
    

    
    



@Test
public void testTagSearchFeedToString() {
    // Arrange
    Meta meta = new Meta();
    meta.setCode(200);
    meta.setErrorType("Success");
    meta.setErrorMessage("No errors");
    
    TagInfoData tag1 = new TagInfoData();
    tag1.setName("tag1");
    TagInfoData tag2 = new TagInfoData();
    tag2.setName("tag2");
    List<TagInfoData> tagList = new ArrayList<>();
    tagList.add(tag1);
    tagList.add(tag2);
    
    TagSearchFeed tagSearchFeed = new TagSearchFeed();
    tagSearchFeed.setMeta(meta);
    tagSearchFeed.setTagList(tagList);
    
    // Act
    String result = tagSearchFeed.toString();
    
    // Assert
    String expected = "TagSearchFeed [meta=Meta{code=200, errorType='Success', errorMessage='No errors'}, tagList=[TagInfoData{name='tag1'}, TagInfoData{name='tag2'}]]";
    assertEquals(expected, result);
}
}
