// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;



import java.util.Arrays;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
    


    

@Test
        public void merge(TestRectangularTextContainer other) {
            // Merge text elements as per focal method
            if (compareTo(other) < 0) {
                this.getTextElements().addAll(other.getTextElements());
            } else {
                this.getTextElements().addAll(0, other.getTextElements());
            }
            // Simulate super.merge: update bounds to min top/left and max width/height
            float newTop = Math.min(this.top, other.top);
            float newLeft = Math.min(this.left, other.left);
            float newRight = Math.max(this.left + this.width, other.left + other.width);
            float newBottom = Math.max(this.top + this.height, other.top + other.height);
            this.top = newTop;
            this.left = newLeft;
            this.width = newRight - newLeft;
            this.height = newBottom - newTop;
        }
}
