// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Caption_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:34:16 GMT 2024
 */
package org.jinstagram.entity.common;


import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Caption;
import org.jinstagram.entity.common.FromTagData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Caption_ESTest extends Caption_ESTest_scaffolding {


    
    
    @Test
    public void testGetFrom() {
        Caption caption = new Caption();
        FromTagData fromTagData = new FromTagData();

        caption.setFrom(fromTagData);

        assertEquals(fromTagData, caption.getFrom());
    }


    
    @Test
    public void testSetText() {
        Caption caption = new Caption();
        String expectedText = "Sample Text";
        
        caption.setText(expectedText);
        
        assertEquals(expectedText, caption.getText());
    }


    
    @Test
    public void testSetId() {
        Caption caption = new Caption();
        String id = "123";
        caption.setId(id);
        assertEquals(id, caption.getId());
    }


    
    @Test
    public void testSetCreatedTime() {
        Caption caption = new Caption();
        String createdTime = "2022-01-01T12:00:00";
        caption.setCreatedTime(createdTime);
        assertEquals(createdTime, caption.getCreatedTime());
    }


    
    @Test
    public void testGetFrom_1() {
        Caption caption = new Caption();
        FromTagData fromTagData = new FromTagData();
        
        caption.setFrom(fromTagData);
        
        assertEquals(fromTagData, caption.getFrom());
    }

}
