// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Comments_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:36:05 GMT 2024
 */
package org.jinstagram.entity.common;



import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.Comments;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.Comments;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.Comments;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Comments_ESTest extends Comments_ESTest_scaffolding {


    


@Test
public void testGetComments() {
    Comments comments = new Comments();
    CommentData comment1 = new CommentData();

    FromTagData fromTagData1 = new FromTagData();
    fromTagData1.setUsername("User1");
    comment1.setCommentFrom(fromTagData1);

    comment1.setText("Great post!");
    CommentData comment2 = new CommentData();

    FromTagData fromTagData2 = new FromTagData();
    fromTagData2.setUsername("User2");
    comment2.setCommentFrom(fromTagData2);

    comment2.setText("Nice photo!");
    List<CommentData> commentList = new LinkedList<CommentData>();
    commentList.add(comment1);
    commentList.add(comment2);
    comments.setComments(commentList);
    List<CommentData> retrievedComments = comments.getComments();
    assertNotNull(retrievedComments);
    assertEquals(commentList.size(), retrievedComments.size());
    for (int i = 0; i < commentList.size(); i++) {
        assertEquals(commentList.get(i), retrievedComments.get(i));
    }
}


    

@Test
public void testSetComments() {
    Comments comments = new Comments();
    List<CommentData> testComments = new LinkedList<CommentData>();

    CommentData comment1 = new CommentData();
    comment1.setCommentFrom(new FromTagData());
    comment1.setId("1");
    comment1.setText("Comment1");
    testComments.add(comment1);

    CommentData comment2 = new CommentData();
    comment2.setCommentFrom(new FromTagData());
    comment2.setId("2");
    comment2.setText("Comment2");
    testComments.add(comment2);

    comments.setComments(testComments);
    List<CommentData> updatedComments = comments.getComments();
    assertNotNull(updatedComments);
    assertEquals(testComments.size(), updatedComments.size());
    for (int i = 0; i < testComments.size(); i++) {
        assertEquals(testComments.get(i).getText(), updatedComments.get(i).getText());
    }
}


    
    @Test
    public void testSetCount() {
        Comments comments = new Comments();
        comments.setCount(5);
        assertEquals(5, comments.getCount());
    }

}
