// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Location_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:46:49 GMT 2024
 */
package org.jinstagram.entity.common;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Location;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Location_ESTest extends Location_ESTest_scaffolding {


    
    @Test
    public void testSetLatitude() {
        Location location = new Location();
        double testLatitude = 37.7749; // Test value

        location.setLatitude(testLatitude);

        assertEquals(testLatitude, location.getLatitude(), 0.0);
    }


    
    @Test
    public void testSetLongitude() {
        Location location = new Location();
        double longitude = 123.45;
        location.setLongitude(longitude);
        assertEquals(longitude, location.getLongitude(), 0.001);
    }


    
    @Test
    public void testSetId() {
        Location location = new Location();
        String id = "12345";
        location.setId(id);
        assertEquals(id, location.getId());
    }


    
    @Test
    public void testSetName() {
        Location location = new Location();
        String testName = "Test Name";
        location.setName(testName);
        assertEquals(testName, location.getName());
    }

}
