// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;
import static org.junit.Assert.*;
import org.junit.Test;
import java.util.List;
import technology.tabula.Line;
import technology.tabula.TextChunk;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {
    @Test
    public void testGetTextElements() {
        // Create a Line object
        Line line = new Line();
        
        // Create TextChunk objects
        TextChunk textChunk1 = new TextChunk("Text 1");
        TextChunk textChunk2 = new TextChunk("Text 2");
        
        // Add TextChunk objects to the Line object
        line.addTextChunk(textChunk1);
        line.addTextChunk(textChunk2);
        
        // Retrieve the list of TextChunk objects using getTextElements()
        List<TextChunk> textElements = line.getTextElements();
        
        // Check if the list is not null
        assertNotNull(textElements);
        
        // Check if the list contains the expected TextChunk objects
        assertEquals(2, textElements.size());
        assertTrue(textElements.contains(textChunk1));
        assertTrue(textElements.contains(textChunk2));
    }
}
