// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Line_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:53:47 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.TextChunk;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Line_ESTest extends Line_ESTest_scaffolding {
@Test
public void testAddTextChunk() {
    Line line = new Line();

    // Create first TextChunk
    TextChunk chunk1 = new TextChunk("Hello", 0, 0, 10, 10);
    line.addTextChunk(chunk1);

    // After adding first chunk, getTextElements should contain it
    List<TextChunk> chunks = line.getTextElements();
    assert chunks.size() == 1 : "Expected 1 text chunk after first addition";
    assert chunks.get(0) == chunk1 : "First chunk should be the one added";

    // Add second TextChunk
    TextChunk chunk2 = new TextChunk("World", 10, 0, 20, 10);
    line.addTextChunk(chunk2);

    // Now getTextElements should contain both chunks
    chunks = line.getTextElements();
    assert chunks.size() == 2 : "Expected 2 text chunks after second addition";
    assert chunks.get(0) == chunk1 : "First chunk should remain first";
    assert chunks.get(1) == chunk2 : "Second chunk should be the one added second";
}
}
