// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/ProjectionProfile_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {
@Test
public void testSmooth() {
    // Test case 1: Simple data with kernelSize 3
    float[] data1 = {1, 2, 3, 4, 5};
    int kernelSize1 = 3;
    float[] expected1 = new float[data1.length];
    // Manually compute expected results with floor of average in window size 3
    // For i=0: average of data[0..1] = (1+2)/3=1 (floor)
    expected1[0] = (float) Math.floor((1 + 2) / 3.0);
    // For i=1: average of data[0..2] = (1+2+3)/3=2
    expected1[1] = (float) Math.floor((1 + 2 + 3) / 3.0);
    // For i=2: average of data[1..3] = (2+3+4)/3=3
    expected1[2] = (float) Math.floor((2 + 3 + 4) / 3.0);
    // For i=3: average of data[2..4] = (3+4+5)/3=4
    expected1[3] = (float) Math.floor((3 + 4 + 5) / 3.0);
    // For i=4: average of data[3..4] = (4+5)/3=3 (floor)
    expected1[4] = (float) Math.floor((4 + 5) / 3.0);

    float[] result1 = ProjectionProfile.smooth(data1, kernelSize1);
    org.junit.Assert.assertArrayEquals(expected1, result1, 0.0f);

    // Test case 2: kernelSize larger than data length
    float[] data2 = {10, 20};
    int kernelSize2 = 5;
    float[] expected2 = new float[data2.length];
    // For i=0: average of data[0..1] = (10+20)/5=6 (floor)
    expected2[0] = (float) Math.floor((10 + 20) / 5.0);
    // For i=1: average of data[0..1] = (10+20)/5=6 (floor)
    expected2[1] = (float) Math.floor((10 + 20) / 5.0);

    float[] result2 = ProjectionProfile.smooth(data2, kernelSize2);
    org.junit.Assert.assertArrayEquals(expected2, result2, 0.0f);

    // Test case 3: kernelSize = 1 (should return floor of original values)
    float[] data3 = {1.9f, 2.5f, 3.7f};
    int kernelSize3 = 1;
    float[] expected3 = new float[data3.length];
    for (int i = 0; i < data3.length; i++) {
        expected3[i] = (float) Math.floor(data3[i]);
    }
    float[] result3 = ProjectionProfile.smooth(data3, kernelSize3);
    org.junit.Assert.assertArrayEquals(expected3, result3, 0.0f);

    // Test case 4: Empty data array
    float[] data4 = {};
    int kernelSize4 = 3;
    float[] result4 = ProjectionProfile.smooth(data4, kernelSize4);
    org.junit.Assert.assertArrayEquals(new float[0], result4, 0.0f);
}
}
