// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {
@Test
public void testOverlapRatio() {
    // Two rectangles that partially overlap
    Rectangle r1 = new Rectangle(0, 0, 10, 10);  // top=0, left=0, width=10, height=10
    Rectangle r2 = new Rectangle(5, 5, 10, 10);  // top=5, left=5, width=10, height=10

    // Calculate expected intersection area:
    // Overlapping rectangle top-left corner: (5,5)
    // Overlapping rectangle bottom-right corner: (10,10)
    // Intersection width = 10 - 5 = 5
    // Intersection height = 10 - 5 = 5
    float expectedIntersectionArea = 5 * 5;

    // Areas of individual rectangles
    float area1 = r1.getArea(); // 10*10 = 100
    float area2 = r2.getArea(); // 10*10 = 100

    // Union area = area1 + area2 - intersectionArea
    float expectedUnionArea = area1 + area2 - expectedIntersectionArea;

    // Expected overlap ratio
    float expectedRatio = expectedIntersectionArea / expectedUnionArea;

    float actualRatio = r1.overlapRatio(r2);

    // Assert that actual ratio is close to expected ratio
    // Allow a small delta for floating point precision
    org.junit.Assert.assertEquals(expectedRatio, actualRatio, 0.0001f);

    // Test with non-overlapping rectangles (ratio should be 0)
    Rectangle r3 = new Rectangle(20, 20, 5, 5);
    float noOverlapRatio = r1.overlapRatio(r3);
    org.junit.Assert.assertEquals(0.0f, noOverlapRatio, 0.0001f);

    // Test with one rectangle fully inside another (ratio should be intersectionArea / unionArea)
    Rectangle r4 = new Rectangle(2, 2, 5, 5);
    float intersectionArea = r4.getArea(); // fully inside r1
    float unionArea = r1.getArea(); // since r4 inside r1, union = r1 area
    float expectedFullInsideRatio = intersectionArea / unionArea;
    float actualFullInsideRatio = r1.overlapRatio(r4);
    org.junit.Assert.assertEquals(expectedFullInsideRatio, actualFullInsideRatio, 0.0001f);

    // Test overlapRatio with the same rectangle (should be 1.0)
    float selfOverlapRatio = r1.overlapRatio(r1);
    org.junit.Assert.assertEquals(1.0f, selfOverlapRatio, 0.0001f);
}
}
