// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {
    @Test
    public void testOverlapRatio() {
        // Create two rectangles for testing
        Rectangle rectangle1 = new Rectangle(0, 0, 5, 5); // Rectangle with top-left corner at (0,0) and width=5, height=5
        Rectangle rectangle2 = new Rectangle(3, 3, 5, 5); // Rectangle with top-left corner at (3,3) and width=5, height=5

        // Calculate the expected overlap ratio manually
        double intersectionWidth = Math.max(0, Math.min(rectangle1.getRight(), rectangle2.getRight()) - Math.max(rectangle1.getLeft(), rectangle2.getLeft()));
        double intersectionHeight = Math.max(0, Math.min(rectangle1.getBottom(), rectangle2.getBottom()) - Math.max(rectangle1.getTop(), rectangle2.getTop()));
        double intersectionArea = Math.max(0, intersectionWidth * intersectionHeight);
        double unionArea = rectangle1.getArea() + rectangle2.getArea() - intersectionArea;
        float expectedOverlapRatio = (float) (intersectionArea / unionArea);

        // Call the method under test
        float actualOverlapRatio = rectangle1.overlapRatio(rectangle2);

        // Assert that the calculated overlap ratio matches the expected value
        Assert.assertEquals(expectedOverlapRatio, actualOverlapRatio, 0.001); // Allowing for a small delta due to floating-point precision
    }
}
