// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;
import java.awt.geom.Point2D;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    
@Test
public void testSetPositionAndRegion() {
    // Arrange
    Point2D point = new Point2D.Double(5.0, 5.0);

    // Act
    point.setLocation(2.0, 8.0);

    // Assert
    assertEquals(2.0, point.getX(), 0.0);
    assertEquals(8.0, point.getY(), 0.0);

    point.setLocation(10.0, 3.0);
    assertEquals(10.0, point.getX(), 0.0);
    assertEquals(3.0, point.getY(), 0.0);

    point.setLocation(7.0, 6.0);
    assertEquals(7.0, point.getX(), 0.0);
    assertEquals(6.0, point.getY(), 0.0);
}
}
