// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/extractors/SpreadsheetExtractionAlgorithm_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:51:32 GMT 2024
 */
package technology.tabula.extractors;



import org.mockito.Mockito;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import technology.tabula.Page;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.Page;
import technology.tabula.Rectangle;
import technology.tabula.Ruling;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SpreadsheetExtractionAlgorithm_ESTest extends SpreadsheetExtractionAlgorithm_ESTest_scaffolding {
    



    
@Test
public void testIsTabular() {
    // Arrange
    Page page = new Page("Example Page Content");
    Table tableWithLines = new Table(3, 3); // Sample table with defined rows and columns
    Table tableWithoutLines = new Table(2, 2); // Sample table without defined rows and columns

    SpreadsheetExtractionAlgorithm sea = new SpreadsheetExtractionAlgorithm();
    sea.MAGIC_HEURISTIC_NUMBER = 0.65f;

    // Act
    boolean result = sea.isTabular(page);

    // Assert
    assertTrue(result);
}
}
