// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/MapUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:13:58 GMT 2024
 */
package org.jinstagram.utils;



import static org.mockito.Mockito.*;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.MapUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MapUtils_ESTest extends MapUtils_ESTest_scaffolding {
    


    
    
    @Test
    public void testDecodeAndAppendEntries() {
        // Given
        Map<String, String> source = new HashMap<>();
        source.put("key1", "value1");
        source.put("key2", "value2");

        Map<String, String> target = new HashMap<>();

        // Mocking URLUtils.percentEncode method
        when(URLUtils.percentEncode("key1")).thenReturn("encodedKey1");
        when(URLUtils.percentEncode("value1")).thenReturn("encodedValue1");
        when(URLUtils.percentEncode("key2")).thenReturn("encodedKey2");
        when(URLUtils.percentEncode("value2")).thenReturn("encodedValue2");

        // When
        MapUtils.decodeAndAppendEntries(source, target);

        // Then
        assertEquals("encodedKey1", target.get("encodedKey1"));
        assertEquals("encodedValue1", target.get("encodedValue1"));
        assertEquals("encodedKey2", target.get("encodedKey2"));
        assertEquals("encodedValue2", target.get("encodedValue2"));
    }
}
