// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/ZapposJson_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:19:12 GMT 2024
 */
package com.zappos.json;



import java.time.LocalDate;
import java.math.BigInteger;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.*;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.JsonConfig;
import com.zappos.json.ZapposJson;
import com.zappos.json.format.JavaDateFormatter;
import com.zappos.json.format.ValueFormatter;
import java.io.File;
import java.io.PipedReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.Writer;
import java.lang.reflect.Array;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.chrono.HijrahEra;
import java.util.Date;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ZapposJson_ESTest extends ZapposJson_ESTest_scaffolding {
    


    
    
    @Test
    public void testGetValueFormatter() {
        ZapposJson zapposJson = new ZapposJson();
        
        // Test for Date class
        ValueFormatter<Object> dateValueFormatter = zapposJson.getValueFormatter(Date.class);
        assertNotNull(dateValueFormatter);
        assertTrue(dateValueFormatter instanceof JavaDateFormatter);
        
        // Test for java.sql.Date class
        ValueFormatter<Object> sqlDateValueFormatter = zapposJson.getValueFormatter(java.sql.Date.class);
        assertNotNull(sqlDateValueFormatter);
        assertTrue(sqlDateValueFormatter instanceof JavaSqlDateFormatter);
        
        // Test for java.sql.Timestamp class
        ValueFormatter<Object> timestampValueFormatter = zapposJson.getValueFormatter(java.sql.Timestamp.class);
        assertNotNull(timestampValueFormatter);
        assertTrue(timestampValueFormatter instanceof JavaTimestampFormatter);
        
        // Test for java.math.BigInteger class
        ValueFormatter<Object> bigIntegerValueFormatter = zapposJson.getValueFormatter(java.math.BigInteger.class);
        assertNotNull(bigIntegerValueFormatter);
        assertTrue(bigIntegerValueFormatter instanceof BigIntegerFormatter);
        
        // Test for java.math.BigDecimal class
        ValueFormatter<Object> bigDecimalValueFormatter = zapposJson.getValueFormatter(java.math.BigDecimal.class);
        assertNotNull(bigDecimalValueFormatter);
        assertTrue(bigDecimalValueFormatter instanceof BigDecimalFormatter);
        
        // Test for LocalDate class if Reflections class is present
        if (Reflections.classPresent("java.time.chrono.ChronoLocalDate")) {
            ValueFormatter<Object> localDateValueFormatter = zapposJson.getValueFormatter(LocalDate.class);
            assertNotNull(localDateValueFormatter);
            assertTrue(localDateValueFormatter instanceof JavaTimeLocalDateFormatter);
            
            // Test for Instant class if Reflections class is present
            ValueFormatter<Object> instantValueFormatter = zapposJson.getValueFormatter(Instant.class);
            assertNotNull(instantValueFormatter);
            assertTrue(instantValueFormatter instanceof JavaTimeInstantFormatter);
        }
    }
}
