// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/EnforceSignedHeaderUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:10:05 GMT 2024
 */
package org.jinstagram.utils;




import org.apache.commons.codec.binary.Hex;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.Charset;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.EnforceSignedHeaderUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class EnforceSignedHeaderUtils_ESTest extends EnforceSignedHeaderUtils_ESTest_scaffolding {

@Test
public void testSignature() throws Exception {
    String clientSecret = "mySecret";
    String message = "testMessage";
    String expectedSignature = "e2a76c7b65d6c1d2305bc9e3e5a0e4f4f7f7a6b3b8af5e40f1b7eec7b9d59d1b";
    String actualSignature = EnforceSignedHeaderUtils.signature(clientSecret, message);
   
}
}