// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/utils/EnforceSignedRequestUtils_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:11:49 GMT 2024
 */
package org.jinstagram.utils;


import java.nio.charset.Charset;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.apache.commons.codec.binary.Hex;
import org.apache.commons.lang3.StringUtils;
import your.package.name.InstagramException;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.fail;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.utils.EnforceSignedRequestUtils;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class EnforceSignedRequestUtils_ESTest extends EnforceSignedRequestUtils_ESTest_scaffolding {
    
    


    
@Test
public void testSignatureGeneration() {
    // Arrange
    String endpoint = "example_endpoint";
    Map<String, String> params = new HashMap<>();
    params.put("param1", "value1");
    params.put("param2", "value2");
    String clientSecret = "example_secret";
    
    // Act
    String expectedSignature = "d1d5a2e55e7d2e1ea9e1a9a4e7a3e2f3e4d8a3f6c5f8b8c9d3b4b8a1f2b7a2";
    
    try {
        String generatedSignature = EnforceSignedRequestUtils.signature(endpoint, params, clientSecret);
        
        // Assert
        assertEquals(expectedSignature, generatedSignature);
    } catch (InstagramException e) {
        fail("Exception occurred: " + e.getMessage());
    }
}
}
