// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/MediaFeedData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:30:23 GMT 2024
 */
package org.jinstagram.entity.users.feed;



import org.jinstagram.entity.common.CommentData;
import org.jinstagram.entity.common.FromTagData;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Caption;
import org.jinstagram.entity.common.Comments;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.Likes;
import org.jinstagram.entity.common.Location;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaFeedData_ESTest extends MediaFeedData_ESTest_scaffolding {
    




@Test
public void testToString() {
    // Arrange
    Caption caption = new Caption();
    caption.setText("Sample caption");

    Comments comments = new Comments();
    comments.setComments(List.of(new CommentData("Sample comment")));

    String createdTime = "2022-01-01";
    String id = "1234";
    String imageFilter = "filter";
    Images images = new Images("image_url");
    Likes likes = new Likes(10);
    String link = "http://samplelink.com";
    Location location = new Location("Sample location");
    List<String> tags = List.of("tag1", "tag2");
    String type = "photo";
    User user = new User("John Doe");
    boolean userHasLiked = true;
    List<UsersInPhoto> usersInPhotoList = List.of(new UsersInPhoto("user1"), new UsersInPhoto("user2"));
    MediaFeedData mediaFeedData = new MediaFeedData();
    
    // Act
    mediaFeedData.setCaption(caption);
    mediaFeedData.setComments(comments);
    mediaFeedData.setCreatedTime(createdTime);
    mediaFeedData.setId(id);
    mediaFeedData.setImageFilter(imageFilter);
    mediaFeedData.setImages(images);
    mediaFeedData.setLikes(likes);
    mediaFeedData.setLink(link);
    mediaFeedData.setLocation(location);
    mediaFeedData.setTags(tags);
    mediaFeedData.setType(type);
    mediaFeedData.setUser(user);
    mediaFeedData.setUserHasLiked(userHasLiked);
    mediaFeedData.setUsersInPhotoList(usersInPhotoList);
    String result = mediaFeedData.toString();
    
    // Assert
    String expected = "MediaFeedData [caption=Sample caption, comments=[Sample comment], createdTime=2022-01-01, id=1234, imageFilter=filter, images=image_url, likes=10, link=http://samplelink.com, location=Sample location, tags=[tag1, tag2], type=photo, user=John Doe, userHasLiked=true, usersInPhotoList=[user1, user2]]";
    Assert.assertEquals(expected, result);
}
}
