// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/UserFeedData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:34:30 GMT 2024
 */
package org.jinstagram.entity.users.feed;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.feed.UserFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserFeedData_ESTest extends UserFeedData_ESTest_scaffolding {
    
@Test
public void testSetProfilePictureUrl() {
    // The test is meant to verify that the setProfilePictureUrl method in UserFeedData correctly sets the profile picture URL and that the getProfilePictureUrl method retrieves the same URL.

    // Arrange
    UserFeedData user = new UserFeedData();
    String newProfilePictureUrl = "https://example.com/profile.jpg";

    // Act
    user.setProfilePictureUrl(newProfilePictureUrl);

    // Assert
    assertEquals(newProfilePictureUrl, user.getProfilePictureUrl());
}
}
