// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/InstagramObject_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:52:13 GMT 2024
 */
package org.jinstagram;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.mockito.Mockito;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.locations.LocationInfo;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramObject_ESTest extends InstagramObject_ESTest_scaffolding {
    @Test
    public void testGetAPILimitStatus() {
        // Given
        InstagramObject instagramObject = Mockito.mock(InstagramObject.class);
        Map<String, String> headers = new HashMap<>();
        headers.put("X-Ratelimit-Limit", "5000");
        headers.put("X-Ratelimit-Remaining", "3000");
        Mockito.when(instagramObject.getHeaders()).thenReturn(headers);

        // When
        int apiLimitStatus = instagramObject.getAPILimitStatus();

        // Then
        assertEquals(5000, apiLimitStatus);
    }
}
