// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:18:17 GMT 2024
 */
package org.jinstagram.entity.tags;


Your import statements here.


import com.google.gson.annotations.SerializedName;
import org.jinstagram.entity.common.TagInfoData;
import org.jinstagram.entity.common.TagSearchFeed;
import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagSearchFeed_ESTest extends TagSearchFeed_ESTest_scaffolding {
    

    


    


@Test
public void testToString() {
    // Arrange
    Meta meta = new Meta();
    meta.setCode(200);
    meta.setErrorType("success");
    meta.setErrorMessage("Tag search successful");

    List<TagInfoData> tagList = new ArrayList<>();
    TagInfoData tagInfoData1 = new TagInfoData();
    tagInfoData1.setTag("nature");
    tagInfoData1.setCount(1500000);
    tagList.add(tagInfoData1);

    TagInfoData tagInfoData2 = new TagInfoData();
    tagInfoData2.setTag("summer");
    tagInfoData2.setCount(800000);
    tagList.add(tagInfoData2);

    TagSearchFeed tagSearchFeed = new TagSearchFeed();
    tagSearchFeed.setMeta(meta);
    tagSearchFeed.setTagList(tagList);

    // Act
    String result = tagSearchFeed.toString();

    // Assert
    assertEquals("TagSearchFeed [meta=Meta{code=200, errorType='success', errorMessage='Tag search successful'}, tagList=[TagInfoData{tag='nature', count=1500000}, TagInfoData{tag='summer', count=800000}]]", result);
}
}
