// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/ProjectionProfile_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:59:46 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Page;
import technology.tabula.ProjectionProfile;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ProjectionProfile_ESTest extends ProjectionProfile_ESTest_scaffolding {
@Test
public void testGetAutocorrelation() {
    // Input projection array with known values
    float[] projection = new float[] {10f, 20f, 30f, 40f, 50f};

    // Expected output calculation:
    // rv length = projection.length - 1 = 4
    // rv[0] = 0 (not set in loop, default 0)
    // rv[1] = (projection[1] * projection[0]) / 100f = (20 * 10) / 100 = 2.0
    // rv[2] = (projection[2] * projection[1]) / 100f = (30 * 20) / 100 = 6.0
    // rv[3] = (projection[3] * projection[2]) / 100f = (40 * 30) / 100 = 12.0
    // Note: projection[4] is not used because loop ends at projection.length - 1
    float[] expected = new float[] {0f, 2.0f, 6.0f, 12.0f};

    float[] actual = ProjectionProfile.getAutocorrelation(projection);

    // Assert length
    org.junit.Assert.assertEquals("Output length mismatch", expected.length, actual.length);

    // Assert values
    for (int i = 0; i < expected.length; i++) {
        org.junit.Assert.assertEquals("Mismatch at index " + i, expected[i], actual[i], 0.0001f);
    }
}
}
