// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
@Test
public void testSetTextElements() {
    // Create a RectangularTextContainer instance with some dummy dimensions
    RectangularTextContainer<TextChunk> container = new RectangularTextContainer<TextChunk>(0, 0, 100, 100) {};

    // Create a list of TextChunk elements to set
    TextChunk chunk1 = new TextChunk(new TextElement("Hello", 0, 0, 10, 10));
    TextChunk chunk2 = new TextChunk(new TextElement("World", 10, 0, 10, 10));
    List<TextChunk> newTextElements = List.of(chunk1, chunk2);

    // Set the new text elements
    container.setTextElements(newTextElements);

    // Retrieve the text elements and verify they were set correctly
    List<TextChunk> retrievedElements = container.getTextElements();

    // Assert that the retrieved list is the same as the one set
    org.junit.Assert.assertEquals(newTextElements, retrievedElements);
}
}
