// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/CohenSutherlandClipping_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 09:46:24 GMT 2024
 */
package technology.tabula;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.awt.geom.Rectangle2D;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.CohenSutherlandClipping;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CohenSutherlandClipping_ESTest extends CohenSutherlandClipping_ESTest_scaffolding {
    
    @Test
    public void testSetClip() {
        Rectangle2D clipWindow = new Rectangle2D.Double(10, 20, 30, 40);
        CohenSutherlandClipping clipping = new CohenSutherlandClipping();
        clipping.setClip(clipWindow);

        Line2D.Float line = new Line2D.Float(5, 25, 35, 55); // Sample line for clipping

        assertTrue(clipping.clip(line)); // Assuming clip method returns true if the line is within the clip window

        // Verify other properties of the clip window
        assertEquals(10.0, clipWindow.getX(), 0.0); // Assuming getX() returns x coordinate of the top left corner
        assertEquals(40.0, clipWindow.getMaxX(), 0.0); // Assuming getMaxX() returns x coordinate of the bottom right corner
        assertEquals(20.0, clipWindow.getY(), 0.0); // Assuming getY() returns y coordinate of the top left corner
        assertEquals(60.0, clipWindow.getMaxY(), 0.0); // Assuming getMaxY() returns y coordinate of the bottom right corner
    }
}
