// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/RectangularTextContainer_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:07:21 GMT 2024
 */
package technology.tabula;




import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Cell;
import technology.tabula.RectangularTextContainer;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RectangularTextContainer_ESTest extends RectangularTextContainer_ESTest_scaffolding {
    
    
    


    @Test
    public void testMerge() {
        // Arrange
        RectangularTextContainer<String> container1 = new RectangularTextContainer<>(0, 0, 100, 50);
        container1.getTextElements().add("First");
        container1.getTextElements().add("Second");

        RectangularTextContainer<String> container2 = new RectangularTextContainer<>(0, 0, 100, 50);
        container2.getTextElements().add("Third");
        container2.getTextElements().add("Fourth");

        // Act
        RectangularTextContainer<String> result = container1.merge(container2);

        // Assert
        List<String> expectedElements = new ArrayList<>();
        expectedElements.add("First");
        expectedElements.add("Second");
        expectedElements.add("Third");
        expectedElements.add("Fourth");

        assertEquals(expectedElements, result.getTextElements());
    }
}
