// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;






import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {
    






@Test
public void testAddMethod() {
    // Arrange
    TextChunk textChunk = new TextChunk(0, 0, 10, 10);
    List<TextElement> elements = new ArrayList<>();
    elements.add(new TextElement(1, 1, 5, 5));
    elements.add(new TextElement(2, 2, 6, 6));

    // Act
    textChunk.add(elements);

    // Assert
    List<TextElement> textChunkElements = textChunk.getElements();
    assertEquals(2, textChunkElements.size());
    assertEquals(1, textChunkElements.get(0).y);
    assertEquals(1, textChunkElements.get(0).x);
    assertEquals(5, textChunkElements.get(0).width);
    assertEquals(5, textChunkElements.get(0).height);
    assertEquals(2, textChunkElements.get(1).y);
    assertEquals(2, textChunkElements.get(1).x);
    assertEquals(6, textChunkElements.get(1).width);
    assertEquals(6, textChunkElements.get(1).height);
}
}
