// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/Comments_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:36:05 GMT 2024
 */
package org.jinstagram.entity.common;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.CommentData;
import org.jinstagram.entity.common.Comments;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Comments_ESTest extends Comments_ESTest_scaffolding {
    @Test
    public void testGetComments() {
        // Create a new instance of Comments
        Comments comments = new Comments();

        // Create some sample CommentData objects
        CommentData comment1 = new CommentData("User1", "Great post!");
        CommentData comment2 = new CommentData("User2", "Nice photo!");

        // Add the sample comments to the Comments object
        List<CommentData> commentList = new LinkedList<>();
        commentList.add(comment1);
        commentList.add(comment2);
        comments.setComments(commentList);

        // Retrieve the comments using getComments()
        List<CommentData> retrievedComments = comments.getComments();

        // Check if the retrieved comments are not null
        assertNotNull(retrievedComments);

        // Check if the number of retrieved comments matches the number of added comments
        assertEquals(commentList.size(), retrievedComments.size());

        // Check if the retrieved comments contain the same elements as the added comments
        for (int i = 0; i < commentList.size(); i++) {
            assertEquals(commentList.get(i), retrievedComments.get(i));
        }
    }
}
