// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/InstagramConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:50:40 GMT 2024
 */
package org.jinstagram;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramConfig_ESTest extends InstagramConfig_ESTest_scaffolding {
    @Test
    public void testIsEnforceSignedRequest() {
        InstagramConfig instagramConfig = new InstagramConfig();
        boolean initialEnforceSignedRequest = instagramConfig.isEnforceSignedRequest();
        assertEquals(false, initialEnforceSignedRequest);

        instagramConfig.setEnforceSignedRequest(true);
        boolean updatedEnforceSignedRequest = instagramConfig.isEnforceSignedRequest();
        assertEquals(true, updatedEnforceSignedRequest);
    }
}
