// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/Counts_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:20:16 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.basicinfo.Counts;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Counts_ESTest extends Counts_ESTest_scaffolding {
@Test
public void testSetFollowedBy() {
    Counts counts = new Counts();
    int newFollowedBy = 123;
    counts.setFollowedBy(newFollowedBy);
    // Since there is no getFollowedBy() method defined in the focal method context,
    // we assume it exists as per the class definition to verify the setter.
    // If getFollowedBy() is not available, this test cannot verify the setter directly.
    assertEquals(newFollowedBy, counts.getFollowedBy());
}
}
