// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/SubscriptionUtil_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:08:27 GMT 2024
 */
package org.jinstagram.realtime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.realtime.SubscriptionUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SubscriptionUtil_ESTest extends SubscriptionUtil_ESTest_scaffolding {
@Test
public void testIsSuccess() {
    // Create an instance of VerificationResult with success = true
    VerificationResult resultTrue = new VerificationResult(true, "dummySignature");
    // Assert that isSuccess() returns true
    assert(resultTrue.isSuccess());

    // Create an instance of VerificationResult with success = false
    VerificationResult resultFalse = new VerificationResult(false, "dummySignature");
    // Assert that isSuccess() returns false
    assert(!resultFalse.isSuccess());
}
}
