// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagInfoData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:12:33 GMT 2024
 */
package org.jinstagram.entity.tags;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.tags.TagInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagInfoData_ESTest extends TagInfoData_ESTest_scaffolding {
@Test
public void testToString() {
    TagInfoData tagInfo = new TagInfoData();
    tagInfo.setMediaCount(12345L);
    tagInfo.setTagName("exampleTag");

    String expected = "TagInfoData [mediaCount=12345, tagName=exampleTag]";
    String actual = tagInfo.toString();

    org.junit.Assert.assertEquals(expected, actual);
}
}
