// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Ruling_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:09:27 GMT 2024
 */
package technology.tabula;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.*;
import technology.tabula.Ruling;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Ruling;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Ruling_ESTest extends Ruling_ESTest_scaffolding {
    
    @Test
    public void testCollapseOrientedRulings() {
        List<Ruling> lines = new ArrayList<>();
        lines.add(new Ruling(0, 0, 10, 10));
        lines.add(new Ruling(5, 5, 15, 15));
        lines.add(new Ruling(20, 20, 5, 5));
        int expandAmount = 2;
        List<Ruling> collapsedLines = Ruling.collapseOrientedRulings(lines, expandAmount);
        assertEquals(2, collapsedLines.size());

        assertEquals(0f, collapsedLines.get(0).getTop(), 0.001);

        assertEquals(0f, collapsedLines.get(0).getLeft(), 0.001);
        assertEquals(15f, collapsedLines.get(0).getWidth(), 0.001);
        assertEquals(15f, collapsedLines.get(0).getHeight(), 0.001);
        assertEquals(20f, collapsedLines.get(1).getTop(), 0.001);
        assertEquals(20f, collapsedLines.get(1).getLeft(), 0.001);
        assertEquals(5f, collapsedLines.get(1).getWidth(), 0.001);
        assertEquals(5f, collapsedLines.get(1).getHeight(), 0.001);
    }
}
