// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/InstagramSubscription_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:59:46 GMT 2024
 */
package org.jinstagram.realtime;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.jinstagram.realtime.InstagramSubscription;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramSubscription_ESTest extends InstagramSubscription_ESTest_scaffolding {

    @Test
    public void testVerifyToken_validAndEmpty() {
        InstagramSubscription subscription = new InstagramSubscription();
        String validToken = "validToken123";
        InstagramSubscription returned = subscription.verifyToken(validToken);
        assertSame(subscription, returned);
        try {
            java.lang.reflect.Field paramsField = InstagramSubscription.class.getDeclaredField("params");
            paramsField.setAccessible(true);
            @SuppressWarnings("unchecked")
            java.util.Map<String, String> params = (java.util.Map<String, String>) paramsField.get(subscription);
            assertEquals(validToken, params.get(Constants.VERIFY_TOKEN));
        } catch (NoSuchFieldException e) {
            fail("Reflection failed: " + e.getMessage());
        } catch (IllegalAccessException e) {
            fail("Reflection failed: " + e.getMessage());
        }
        try {
            subscription.verifyToken("");
            fail("Expected IllegalArgumentException for empty verifyToken");
        } catch (IllegalArgumentException e) {
            assertEquals("Invalid 'verifyToken' key", e.getMessage());
        }
        try {
            subscription.verifyToken(null);
            fail("Expected IllegalArgumentException for null verifyToken");
        } catch (IllegalArgumentException e) {
            assertEquals("Invalid 'verifyToken' key", e.getMessage());
        }
    }
}
