// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/MediaFeedData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:30:23 GMT 2024
 */
package org.jinstagram.entity.users.feed;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Caption;
import org.jinstagram.entity.common.Comments;
import org.jinstagram.entity.common.Images;
import org.jinstagram.entity.common.Likes;
import org.jinstagram.entity.common.Location;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.common.UsersInPhoto;
import org.jinstagram.entity.common.Videos;
import org.jinstagram.entity.users.feed.CarouselMedia;
import org.jinstagram.entity.users.feed.MediaFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class MediaFeedData_ESTest extends MediaFeedData_ESTest_scaffolding {

@Test
public void testSetTags() {
    // Arrange:
    MediaFeedData mediaFeedData = new MediaFeedData();

    List<String> initialTags = new LinkedList<String>();
    initialTags.add("nature");
    initialTags.add("sunset");

    // Act:
    mediaFeedData.setTags(initialTags);
    List<String> retrievedTags = mediaFeedData.getTags();

    // Assert:
    assertNotNull(retrievedTags);
    assertEquals(2, retrievedTags.size());
    assertTrue(retrievedTags.contains("nature"));
    assertTrue(retrievedTags.contains("sunset"));

    // Arrange:
    List<String> newTags = new LinkedList<String>();
    newTags.add("travel");
    newTags.add("adventure");
    newTags.add("photography");

    // Act:
    mediaFeedData.setTags(newTags);
    retrievedTags = mediaFeedData.getTags();

    // Assert:
    assertNotNull(retrievedTags);
    assertEquals(3, retrievedTags.size());
    assertTrue(retrievedTags.contains("travel"));
    assertTrue(retrievedTags.contains("adventure"));
    assertTrue(retrievedTags.contains("photography"));

    // Act:
    mediaFeedData.setTags(null);

    // Assert:
    assertNull(mediaFeedData.getTags());
}
}
