// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/feed/UserFeedData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:34:30 GMT 2024
 */
package org.jinstagram.entity.users.feed;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.feed.UserFeedData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserFeedData_ESTest extends UserFeedData_ESTest_scaffolding {
@Test
public void testToString() {
    UserFeedData userFeedData = new UserFeedData();
    userFeedData.setId("12345");
    userFeedData.setProfilePictureUrl("http://example.com/pic.jpg");
    userFeedData.setUserName("testuser");
    userFeedData.setFullName("Test User");
    userFeedData.setWebsite("http://example.com");
    userFeedData.setBio("This is a test bio.");

    String expected = "UserFeedData [id=12345, profilePictureUrl=http://example.com/pic.jpg, userName=testuser, fullName=Test User, website=http://example.com, bio=This is a test bio.]";
    String actual = userFeedData.toString();

    org.junit.Assert.assertEquals(expected, actual);
}
}
