// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/Zappos_zappos-json/src/test/java/com/zappos/json/util/TypeImpl_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:15:15 GMT 2024
 */
package com.zappos.json.util;
import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.TypeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TypeImpl_ESTest extends TypeImpl_ESTest_scaffolding {
    @Test
    public void testGetIterableImpl() {
        // Case 1: Input is List.class -> should map to ArrayList.class
        TypeImpl ti1 = TypeImpl.getIterableImpl(List.class);
        assertEquals(List.class, ti1.getInfClass());
        assertEquals(ArrayList.class, ti1.getImplClass());

        // Case 2: Input is Collection.class -> should map to ArrayList.class
        TypeImpl ti2 = TypeImpl.getIterableImpl(Collection.class);
        assertEquals(Collection.class, ti2.getInfClass());
        assertEquals(ArrayList.class, ti2.getImplClass());

        // Case 3: Input is Iterable.class -> should map to ArrayList.class
        TypeImpl ti3 = TypeImpl.getIterableImpl(Iterable.class);
        assertEquals(Iterable.class, ti3.getInfClass());
        assertEquals(ArrayList.class, ti3.getImplClass());

        // Case 4: Input is a concrete class implementing Iterable (e.g. LinkedList.class)
        TypeImpl ti4 = TypeImpl.getIterableImpl(LinkedList.class);
        assertEquals(LinkedList.class, ti4.getInfClass());
        assertEquals(LinkedList.class, ti4.getImplClass());

        // Case 5: Input is an interface other than List/Collection/Iterable (e.g. Set.class) -> should throw RuntimeException
        try {
            TypeImpl.getIterableImpl(Set.class);
            fail("Expected RuntimeException for interface without known implementation");
        } catch (RuntimeException e) {
            assertTrue(e.getMessage().contains("Cannot find appropriate implementation"));
        }

        // Case 6: Input is an abstract class (e.g. AbstractList.class) -> should throw RuntimeException
        try {
            TypeImpl.getIterableImpl(AbstractList.class);
            fail("Expected RuntimeException for abstract class without known implementation");
        } catch (RuntimeException e) {
            assertTrue(e.getMessage().contains("Cannot find appropriate implementation"));
        }
    }
}
