// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/relationships/RelationshipData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:09:00 GMT 2024
 */
package org.jinstagram.entity.relationships;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.relationships.RelationshipData;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.relationships.RelationshipData;
import org.junit.runner.RunWith;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.relationships.RelationshipData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class RelationshipData_ESTest extends RelationshipData_ESTest_scaffolding {


    
    @Test
    public void testSetTargetUserPrivate() {
        RelationshipData relationshipData = new RelationshipData();
        
        // Test when target user is private
        relationshipData.setTargetUserPrivate(true);
        assertTrue(relationshipData.isTargetUserPrivate());
        
        // Test when target user is not private
        relationshipData.setTargetUserPrivate(false);
        assertFalse(relationshipData.isTargetUserPrivate());
    }


    
    @Test
    public void testSetOutgoingStatus() {
        // Given
        RelationshipData relationshipData = new RelationshipData();
        String expectedOutgoingStatus = "testOutgoingStatus";

        // When
        relationshipData.setOutgoingStatus(expectedOutgoingStatus);

        // Then
        assertEquals(expectedOutgoingStatus, relationshipData.getOutgoingStatus());
    }


    
    @Test
    public void testSetIncomingStatus() {
        RelationshipData relationshipData = new RelationshipData();
        
        // Test setting incoming status to a specific value
        String testIncomingStatus = "Test Status";
        relationshipData.setIncomingStatus(testIncomingStatus);
        assertEquals(testIncomingStatus, relationshipData.getIncomingStatus());
        
        // Test setting incoming status to null
        relationshipData.setIncomingStatus(null);
        assertEquals(null, relationshipData.getIncomingStatus());
        
        // Additional test cases can be added here for more comprehensive coverage
    }


    
    @Test
    public void testSetTargetUserPrivate_1() {
        RelationshipData relationshipData = new RelationshipData();

        // Test setting targetUserPrivate to true
        relationshipData.setTargetUserPrivate(true);
        assertTrue(relationshipData.isTargetUserPrivate());

        // Test setting targetUserPrivate to false
        relationshipData.setTargetUserPrivate(false);
        assertFalse(relationshipData.isTargetUserPrivate());
    }


    
    @Test
    public void testSetOutgoingStatus_1() {
        RelationshipData relationshipData = new RelationshipData();
        String outgoingStatus = "testOutgoingStatus";
        relationshipData.setOutgoingStatus(outgoingStatus);
        assertEquals(outgoingStatus, relationshipData.getOutgoingStatus());
    }

}
