// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/oembed/OembedInformation_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:07:06 GMT 2024
 */
package org.jinstagram.entity.oembed;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OembedInformation_ESTest extends OembedInformation_ESTest_scaffolding {
    
    @Test
    public void testToString() {
        OembedInformation oembedInformation = new OembedInformation();
        oembedInformation.setProviderUrl("https://example.com/provider");
        oembedInformation.setTitle("Sample Title");
        oembedInformation.setUrl("https://example.com/sample");
        oembedInformation.setAuthorName("John Doe");
        oembedInformation.setHeight("100");
        oembedInformation.setWidth("200");
        oembedInformation.setMediaId("12345");
        oembedInformation.setVersion("1.0");
        oembedInformation.setAuthorUrl("https://example.com/author");
        oembedInformation.setProviderName("Sample Provider");
        oembedInformation.setType("video");

        String expected = "OembedInformation [provider_url=https://example.com/provider, title=Sample Title, url=https://example.com/sample, author_name=John Doe, height=100, width=200, version=1.0, author_url=https://example.com/author, provider_name=Sample Provider, type=video, mediaId=12345]";
        assertEquals(expected, oembedInformation.toString());
    }
}
