// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/tags/TagSearchFeed_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:18:17 GMT 2024
 */
package org.jinstagram.entity.tags;



import java.util.ArrayList;
import java.util.*;
import java.lang.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.Meta;
import org.jinstagram.entity.tags.TagInfoData;
import org.jinstagram.entity.tags.TagSearchFeed;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TagSearchFeed_ESTest extends TagSearchFeed_ESTest_scaffolding {
    


    
    
    @Test
    public void testSetTagList() {
        // Given
        TagSearchFeed tagSearchFeed = new TagSearchFeed();
        List<TagInfoData> newTagList = new ArrayList<>();
        newTagList.add(new TagInfoData("Tag1"));
        newTagList.add(new TagInfoData("Tag2"));

        // When
        tagSearchFeed.setTagList(newTagList);

        // Then
        assertEquals(2, tagSearchFeed.getTagList().size());
        assertEquals("Tag1", tagSearchFeed.getTagList().get(0).getName());
        assertEquals("Tag2", tagSearchFeed.getTagList().get(1).getName());
    }
}
