// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/users/basicinfo/UserInfoData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:24:13 GMT 2024
 */
package org.jinstagram.entity.users.basicinfo;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.users.basicinfo.Counts;
import org.jinstagram.entity.users.basicinfo.UserInfoData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UserInfoData_ESTest extends UserInfoData_ESTest_scaffolding {
    

@Test
public void testToString() {
    UserInfoData userInfoData = new UserInfoData();
    userInfoData.setBio("User bio");
    Counts counts = new Counts();
    userInfoData.setCounts(counts);
    userInfoData.setFirstName("John");
    userInfoData.setId("12345");

    // Fixing the buggy line by using the correct method name
    userInfoData.setLast_name("Doe");

    userInfoData.setProfilePicture("profile.jpg");
    userInfoData.setUsername("johndoe");
    userInfoData.setFullName("John Doe");
    userInfoData.setWebsite("www.johndoe.com");
    userInfoData.setBusiness(true);
    String result = userInfoData.toString();
    String expected = "UserInfoData [bio=User bio, counts=" + counts.toString() + ", first_name=John, id=12345, last_name=Doe, profile_picture=profile.jpg, username=johndoe, fullName=John Doe, website=www.johndoe.com, isBusiness=true]";
    assertEquals(expected, result);
}
}
