// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/Rectangle_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:03:59 GMT 2024
 */
package technology.tabula;
import org.junit.Test;
import java.awt.geom.Point2D;
import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Rectangle;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class Rectangle_ESTest extends Rectangle_ESTest_scaffolding {
    @Test
    public void testGetPoints() {
        // Given
        Rectangle rectangle = new Rectangle(0, 0, 5, 3);
        
        // When
        Point2D[] points = rectangle.getPoints();
        
        // Then
        Point2D[] expectedPoints = {
            new Point2D.Float(0, 0),
            new Point2D.Float(5, 0),
            new Point2D.Float(5, 3),
            new Point2D.Float(0, 3)
        };
        
        assert Arrays.equals(expectedPoints, points);
    }
}
