// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/InstagramObject_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:52:13 GMT 2024
 */
package org.jinstagram;





import static org.mockito.Mockito.mockStatic;
import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Map;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.comments.MediaCommentResponse;
import org.jinstagram.entity.locations.LocationInfo;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramObject_ESTest extends InstagramObject_ESTest_scaffolding {



    
    
    
    
    @Test
    public void testGetRemainingLimitStatus() {
        Map<String, String> headers = new HashMap<>();
        headers.put("X-RateLimit-Remaining", "42");

        InstagramObject instagramObject = new InstagramObjectImpl(headers);

        try (MockedStatic<APILimitUtils> utilities = mockStatic(APILimitUtils.class)) {
            utilities.when(() -> APILimitUtils.getRemainingLimitStatus(headers)).thenReturn(42);

            int remaining = instagramObject.getRemainingLimitStatus();

            assertEquals(42, remaining, "The remaining limit status should be 42");
        }
    }
}
