// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/InstagramConfig_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:50:40 GMT 2024
 */
package org.jinstagram;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.InstagramConfig;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class InstagramConfig_ESTest extends InstagramConfig_ESTest_scaffolding {
@Test
public void testGetBaseURI() {
    InstagramConfig config = new InstagramConfig();
    String baseURI = config.getBaseURI();
    // Assuming Constants.BASE_URI is the expected default value
    // Since Constants is not accessible here, we just check that baseURI is not null or empty
    // and matches the initial value set by the constructor.
    // If you know the expected value, replace "https://api.instagram.com" with that.
    String expectedBaseURI = "https://api.instagram.com"; // replace with actual expected value if known
    org.junit.Assert.assertNotNull("Base URI should not be null", baseURI);
    org.junit.Assert.assertFalse("Base URI should not be empty", baseURI.isEmpty());
    org.junit.Assert.assertEquals("Base URI should match the expected default", expectedBaseURI, baseURI);
}
}
