// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/oembed/OembedInformation_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 04:07:06 GMT 2024
 */
package org.jinstagram.entity.oembed;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.oembed.OembedInformation;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class OembedInformation_ESTest extends OembedInformation_ESTest_scaffolding {
@Test
public void testSetHeight() {
    OembedInformation info = new OembedInformation();
    String testHeight = "480";
    info.setHeight(testHeight);
    // Since there is no getHeight() method defined in the focal method context,
    // we rely on toString() to verify the height was set correctly.
    // This assumes toString() includes the height field in its output.
    String toStringOutput = info.toString();
    assert toStringOutput != null && toStringOutput.contains(testHeight) : "Height was not set correctly";
}
}
