// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/realtime/SubscriptionResponseData_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 05:02:29 GMT 2024
 */
package org.jinstagram.realtime;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.realtime.SubscriptionResponseData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SubscriptionResponseData_ESTest extends SubscriptionResponseData_ESTest_scaffolding {
@Test
public void testSetAspect() {
    SubscriptionResponseData data = new SubscriptionResponseData();
    String testAspect = "update";
    data.setAspect(testAspect);
    // Since there is no getAspect() method defined in the focal context, 
    // we assume it exists as per the initial context to verify the set operation.
    // If getAspect() is not available, this test cannot verify the internal state.
    assertEquals(testAspect, data.getAspect());
}
}
