// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/sachin-handiekar_jInstagram/src/test/java/org/jinstagram/entity/common/UsersInPhoto_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 27 03:53:50 GMT 2024
 */
package org.jinstagram.entity.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jinstagram.entity.common.GridPosition;
import org.jinstagram.entity.common.User;
import org.jinstagram.entity.common.UsersInPhoto;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class UsersInPhoto_ESTest extends UsersInPhoto_ESTest_scaffolding {
@Test
public void testGetPosition() {
    UsersInPhoto usersInPhoto = new UsersInPhoto();
    GridPosition expectedPosition = new GridPosition();
    expectedPosition.setX(0.5f);
    expectedPosition.setY(0.75f);
    usersInPhoto.setPosition(expectedPosition);

    GridPosition actualPosition = usersInPhoto.getPosition();

    // Assert that the returned position is the same as the one set
    org.junit.Assert.assertNotNull(actualPosition);
    org.junit.Assert.assertEquals(expectedPosition.getX(), actualPosition.getX(), 0.0001);
    org.junit.Assert.assertEquals(expectedPosition.getY(), actualPosition.getY(), 0.0001);
}
}
