// original test path: /Users/curtis/Github/Thesis/chatTester/Repos/tabulapdf_tabula-java/src/test/java/technology/tabula/TextChunk_ESTest.java
/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 10 10:15:23 GMT 2024
 */
package technology.tabula;

import java.util.*;
import java.lang.*;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import technology.tabula.Line;
import technology.tabula.Rectangle;
import technology.tabula.TextChunk;
import technology.tabula.TextElement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class TextChunk_ESTest extends TextChunk_ESTest_scaffolding {

@Test
public void testAllSameChar() {
    class TestTextChunk extends TextChunk {
        private final String text;
        TestTextChunk(String text) {
            super(0, 0, 0, 0);
            this.text = text;
        }
        @Override
        public String getText() {
            return text;
        }
        @Override
        public boolean isSameChar(Character c) {
            if (text.isEmpty()) return false;
            return text.charAt(0) == c;
        }
    }
    List<TextChunk> emptyList = new ArrayList<>();
    assert !TextChunk.allSameChar(emptyList);
    List<TextChunk> singleList = new ArrayList<>();
    singleList.add(new TestTextChunk("a"));
    assert !TextChunk.allSameChar(singleList);
    List<TextChunk> allEmpty = new ArrayList<>();
    allEmpty.add(new TestTextChunk(""));
    allEmpty.add(new TestTextChunk(""));
    assert !TextChunk.allSameChar(allEmpty);
    List<TextChunk> firstNonEmptyRestEmpty = new ArrayList<>();
    firstNonEmptyRestEmpty.add(new TestTextChunk("a"));
    firstNonEmptyRestEmpty.add(new TestTextChunk(""));
    firstNonEmptyRestEmpty.add(new TestTextChunk(""));
    assert !TextChunk.allSameChar(firstNonEmptyRestEmpty);
    List<TextChunk> allSameChar = new ArrayList<>();
    allSameChar.add(new TestTextChunk("apple"));
    allSameChar.add(new TestTextChunk("aardvark"));
    allSameChar.add(new TestTextChunk("ant"));
    assert TextChunk.allSameChar(allSameChar);
    List<TextChunk> differentStartChar = new ArrayList<>();
    differentStartChar.add(new TestTextChunk("apple"));
    differentStartChar.add(new TestTextChunk("banana"));
    differentStartChar.add(new TestTextChunk("ant"));
    assert !TextChunk.allSameChar(differentStartChar);
    List<TextChunk> mixedEmptyNonEmpty = new ArrayList<>();
    mixedEmptyNonEmpty.add(new TestTextChunk(""));
    mixedEmptyNonEmpty.add(new TestTextChunk("cat"));
    mixedEmptyNonEmpty.add(new TestTextChunk(""));
    mixedEmptyNonEmpty.add(new TestTextChunk("car"));
    assert TextChunk.allSameChar(mixedEmptyNonEmpty);
}
}
